# **UE4: NumPy**

# **Chapter 02:** NumPy Basics

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/512px-NumPy_logo_2020.svg.png" height="150">

## 🌟 Introduction

In this chapter, we'll explore the fundamental building blocks of NumPy - arrays. Arrays are the core data structure in NumPy that enable efficient numerical computing. Understanding how to create, manipulate, and access elements in NumPy arrays is essential for any data-related task in Python.

NumPy arrays offer significant advantages over Python's built-in lists when working with numerical data. With optimized storage and specialized functions, NumPy arrays provide the foundation upon which virtually all scientific computing in Python is built. Mastering these basics will empower you to efficiently process and analyze data in your future projects.

> **Tip:** Try to think in terms of operations on entire arrays rather than individual elements. This "vectorized" thinking is key to writing efficient NumPy code and is a valuable skill that transfers to other data science libraries.

## 📚 Chapter Outline

### [Chapter 2.1: Introduction to NumPy Arrays](#chapter-21-introduction-to-numpy-arrays)
- **[Array Creation Methods:](#-array-creation-methods)** Different ways to initialize arrays in NumPy.
- **[Array Data Types:](#-array-data-types)** Understanding the various data types available in NumPy.
- **[Multi-dimensional Arrays:](#-multi-dimensional-arrays)** Creating and understanding arrays with multiple dimensions.

### [Chapter 2.2: Array Attributes](#chapter-22-array-attributes)
- **[Shape and Size:](#-shape-and-size)** Understanding the dimensions and element count of arrays.
- **[Data Type Information:](#-data-type-information)** Examining and manipulating array data types.
- **[Dimensionality:](#-dimensionality)** Working with the number of dimensions in an array.

### [Chapter 2.3: Indexing Techniques](#chapter-23-indexing-techniques)
- **[Basic Indexing:](#-basic-indexing)** Accessing individual elements and subarrays.
- **[Boolean Indexing:](#-boolean-indexing)** Selecting elements based on conditions.
- **[Fancy Indexing:](#-fancy-indexing)** Using arrays of indices to extract elements.

### [Chapter 2.4: Slicing Techniques](#chapter-24-slicing-techniques)
- **[Basic Slicing:](#-basic-slicing)** Extracting portions of arrays using slice notation.
- **[Multi-dimensional Slicing:](#-multi-dimensional-slicing)** Working with slices across multiple dimensions.
- **[Views vs. Copies:](#-views-vs-copies)** Understanding the difference between array views and copies.

### [Chapter 2.5: Coding Challenge](#chapter-25-coding-challenge)
- **[Stress Analysis 1/3:](#-stress-analysis-13)** Applying basic array techniques to analyze stress distribution in a metal pole.

## 💡 What You Will Learn

By the end of this chapter, you will be able to:
- Create NumPy arrays using various initialization methods
- Understand and manipulate array attributes like shape, size, and data type
- Access specific elements and subarrays using different indexing techniques
- Extract portions of arrays using slicing operations
- Apply these fundamental array operations to solve a real engineering problem

---
---

## **Chapter 2.1:** Introduction to NumPy Arrays

### 🔍 Array Creation Methods

NumPy arrays are the foundation of numerical computing in Python. Unlike Python lists, NumPy arrays are homogeneous (all elements have the same data type) and stored in a contiguous block of memory, which makes operations on them significantly faster.

There are multiple ways to create NumPy arrays, each suited for different scenarios. Understanding these methods will help you efficiently initialize arrays for your specific needs.

### 🧩 Important Components

* **np.array()**: Creates an array from a Python sequence (list, tuple, etc.)
* **Array creation functions**: Specialized functions for creating arrays with specific patterns
  * `np.zeros()`: Creates an array filled with zeros
  * `np.ones()`: Creates an array filled with ones
  * `np.arange()`: Creates an array with a sequence of numbers
  * `np.linspace()`: Creates an array with evenly spaced values within a range
  * `np.random.random()`: Creates an array with random values

| Function | Purpose | Example | Result |
|----------|---------|---------|--------|
| `np.array()` | Convert sequence to array | `np.array([1,2,3])` | `array([1, 2, 3])` |
| `np.zeros()` | Create array of zeros | `np.zeros(3)` | `array([0., 0., 0.])` |
| `np.ones()` | Create array of ones | `np.ones((2,2))` | `array([[1., 1.], [1., 1.]])` |
| `np.arange()` | Create sequence | `np.arange(0,5)` | `array([0, 1, 2, 3, 4])` |
| `np.linspace()` | Create evenly spaced points | `np.linspace(0,1,5)` | `array([0., 0.25, 0.5, 0.75, 1.])` |

### 📘 Main Content

#### Creating Arrays from Python Sequences

The most direct way to create a NumPy array is from an existing Python sequence, like a list or tuple, using the `np.array()` function:


In [ ]:
import numpy as np

# Creating a 1D array from a list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
print(array_1d)  # Output: [1 2 3 4 5]

# Creating a 2D array from a list of lists
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)
print(array_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]


Note how the printed representation differs from Python lists - this reflects the different internal structure of NumPy arrays.

#### Array Creation Functions

NumPy provides specialized functions for creating arrays with specific patterns:

##### Arrays Filled with Constants


In [ ]:
# Create an array of zeros
zeros_array = np.zeros(5)  # 1D array with 5 zeros
print(zeros_array)  # Output: [0. 0. 0. 0. 0.]

# Create a 2D array of ones
ones_array = np.ones((3, 4))  # 3x4 array filled with ones
print(ones_array)
# Output:
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

# Create an array filled with a specific value
full_array = np.full((2, 3), 7)  # 2x3 array filled with 7
print(full_array)
# Output:
# [[7 7 7]
#  [7 7 7]]


Note that by default, `np.zeros()` and `np.ones()` create arrays of floating-point numbers. You can specify a different data type using the `dtype` parameter (more on data types in the next section).

##### Sequence Generation


In [ ]:
# Create a sequence with integers from 0 to 9
range_array = np.arange(10)
print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]

# Create a sequence with a custom step
step_array = np.arange(0, 10, 2)
print(step_array)  # Output: [0 2 4 6 8]

# Create a sequence with evenly spaced values
linear_array = np.linspace(0, 1, 5)  # 5 evenly spaced points between 0 and 1
print(linear_array)  # Output: [0.   0.25 0.5  0.75 1.  ]


`np.arange()` is similar to Python's built-in `range()` function but returns a NumPy array. `np.linspace()` is particularly useful for creating arrays with a specified number of points evenly spaced between a start and end value.

##### Random Arrays

NumPy's random module offers functions for generating arrays with random values:


In [ ]:
# Create an array with random values between 0 and 1
random_array = np.random.random((2, 3))
print(random_array)
# Output might be:
# [[0.42 0.72 0.31]
#  [0.57 0.14 0.69]]

# Create an array with random integers
random_integers = np.random.randint(0, 10, (3, 3))
print(random_integers)
# Output might be:
# [[2 5 1]
#  [9 8 3]
#  [4 0 7]]


Random arrays are particularly useful for simulations, statistical analysis, and initializing parameters in machine learning algorithms.

#### ⚠️ Common Mistakes with Array Creation

* **Forgetting shape tuples**: Functions like `np.zeros()` expect a tuple for multidimensional arrays: `np.zeros((3, 4))` not `np.zeros(3, 4)`.
* **Mixing data types**: If you create an array with mixed data types, NumPy will "upcast" to accommodate all values, which might not be what you intended.
* **Confusion between `arange()` and `linspace()`**: `arange()` takes a step size, while `linspace()` takes the number of points.

#### 🔄 Quick Check: Array Creation

Which of the following will create a 3x3 identity matrix (ones on the diagonal, zeros elsewhere)?

A) `np.ones((3, 3))`
B) `np.identity(3)`
C) `np.eye(3)`
D) `np.diag([1, 1, 1])`

<details>
   <summary>View Answer</summary>

   The correct answers are B and C.

   Both `np.identity(3)` and `np.eye(3)` create a 3x3 identity matrix. `np.ones((3, 3))` creates a matrix filled with all ones. `np.diag([1, 1, 1])` also creates an identity matrix from the given diagonal elements.
</details>

### 🔍 Array Data Types

NumPy arrays have a fixed data type for all elements, which allows for optimized memory usage and faster operations. Understanding and controlling these data types is crucial for efficient numerical computing.

NumPy provides a rich set of data types, including:

* **Integers**: `int8`, `int16`, `int32`, `int64`, `uint8`, `uint16`, `uint32`, `uint64`
* **Floating-point**: `float16`, `float32`, `float64` (default), `float128`
* **Complex**: `complex64`, `complex128`
* **Boolean**: `bool`
* **String**: `string_` or `unicode_`

The number in each data type name indicates the number of bits used for storage. For example, `int8` uses 8 bits (1 byte) per element, allowing values from -128 to 127.


In [ ]:
# Creating arrays with specific data types
int_array = np.array([1, 2, 3], dtype=np.int8)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float32)
bool_array = np.array([True, False, True], dtype=np.bool_)

print(f"Integer array dtype: {int_array.dtype}")
print(f"Float array dtype: {float_array.dtype}")
print(f"Boolean array dtype: {bool_array.dtype}")


You can also convert between data types using the `astype()` method:


In [ ]:
# Converting between data types
float_array = np.array([1.1, 2.2, 3.8])
int_array = float_array.astype(np.int64)  # Truncates, doesn't round

print(float_array)  # Output: [1.1 2.2 3.8]
print(int_array)    # Output: [1 2 3]


Choosing the appropriate data type is important for:
* **Memory efficiency**: Using the smallest data type that accommodates your data range can save significant memory, especially for large arrays.
* **Computational performance**: Some operations are faster with certain data types.
* **Precision requirements**: For scientific calculations, you might need higher precision (`float64` or `float128`).

#### ⚠️ Common Mistakes with Data Types

* **Precision loss**: Converting from higher to lower precision (e.g., `float64` to `float32`) can lose information.
* **Overflow/underflow**: Using a data type too small for your data range can cause overflow or underflow errors.
* **Assuming integer division**: In NumPy, dividing two integers might still result in a float.

#### 🔄 Quick Check: Data Types

What will be the output of the following code?


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 3.0])

print(a.dtype)
print(b.dtype)
print(a + b)
print((a + b).dtype)


<details>
   <summary>View Answer</summary>

   Output:
   ```
   int64
   float64
   [2. 4. 6.]
   float64
   ```

   When arrays of different data types are operated upon, NumPy follows type promotion rules. In this case, `int64` is promoted to `float64` in the addition operation, and the result has type `float64`.
</details>

### 🔍 Multi-dimensional Arrays

One of NumPy's most powerful features is its ability to work with multi-dimensional arrays. These arrays can represent vectors (1D), matrices (2D), and tensors (3D or more), making them suitable for a wide range of scientific and engineering applications.

#### Creating Multi-dimensional Arrays


In [ ]:
# Creating a 1D array (vector)
vector = np.array([1, 2, 3, 4])
print(f"Vector shape: {vector.shape}")  # Output: (4,)

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix shape: {matrix.shape}")  # Output: (2, 3)

# Creating a 3D array (tensor)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Tensor shape: {tensor.shape}")  # Output: (2, 2, 2)


You can also use the array creation functions we've seen to generate multi-dimensional arrays:


In [ ]:
# Creating multi-dimensional arrays with zeros, ones, etc.
zeros_2d = np.zeros((3, 4))  # 3x4 matrix of zeros
ones_3d = np.ones((2, 3, 2))  # 2x3x2 tensor of ones


#### Understanding Dimensions

In a multi-dimensional array, the shape tuple indicates the size of each dimension. For example, in a shape of `(2, 3, 4)`:
* The first dimension has size 2
* The second dimension has size 3
* The third dimension has size 4

This corresponds to 2 "layers", each containing a 3×4 matrix, for a total of 2×3×4 = 24 elements.

#### Reshaping Arrays

You can change the shape of an array using the `reshape()` method, as long as the total number of elements remains the same:


In [ ]:
# Reshaping arrays
arr = np.arange(12)  # 1D array: [0 1 2 3 4 5 6 7 8 9 10 11]
print(arr)

# Reshape to a 3x4 matrix
matrix = arr.reshape(3, 4)
print(matrix)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Reshape to a 2x2x3 tensor
tensor = arr.reshape(2, 2, 3)
print(tensor)
# Output:
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]


When reshaping, the new shape must be compatible with the original array's size. For example, you can reshape a 12-element array into shapes like `(3, 4)`, `(4, 3)`, `(2, 6)`, or `(2, 2, 3)`, but not into shapes like `(5, 2)` because 5×2 = 10, which doesn't match the original 12 elements.

#### ⚠️ Common Mistakes with Multi-dimensional Arrays

* **Inconsistent dimensions**: When creating arrays from nested lists, ensure all sub-lists have the same length.
* **Forgetting about order**: NumPy arrays are stored in row-major order by default (C-style), which affects how elements are laid out in memory.
* **Shape mismatch**: Operations between arrays require compatible shapes, following NumPy's broadcasting rules.

#### 🔄 Quick Check: Multi-dimensional Arrays

How would you create a 3×3 identity matrix and then stack two of them to form a 2×3×3 tensor?

<details>
   <summary>View Answer</summary>


In [ ]:
   import numpy as np

   # Create a 3x3 identity matrix
   identity = np.eye(3)

   # Stack two copies to create a 2x3x3 tensor
   tensor = np.stack([identity, identity])

   print(tensor.shape)  # Output: (2, 3, 3)


   Alternatively, you could use:

In [ ]:
   tensor = np.repeat(identity[np.newaxis, :, :], 2, axis=0)

</details>

#### 📚 Further Reading: NumPy Arrays

* [NumPy Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html) - Official documentation
* [NumPy Data Types](https://numpy.org/doc/stable/reference/arrays.dtypes.html) - Detailed information on data types
* [NumPy: The Absolute Basics for Beginners](https://numpy.org/doc/stable/user/absolute_beginners.html) - Official beginner's guide

---

## 👨‍💻 **Practice Tasks 2.1:** Creating and Understanding Arrays

Now it's time to practice creating and exploring various types of NumPy arrays. Complete the following tasks:

**Basic array creation:**

1. Create a 1D array of integers from 0 to 9 using `np.array()`.

2. Create a 1D array of even numbers from 0 to 20 using `np.arange()`.

3. Create a 2D array of shape (3, 4) filled with zeros.

4. Create a 3×3 identity matrix.

5. Create an array of 5 evenly spaced values between 0 and 1 using `np.linspace()`.

**Working with data types:**

6. Create an array of integers and check its data type.

7. Create the same array but explicitly set its data type to `np.float64`, then check the data type.

8. Create an array of floats (e.g., [1.5, 2.5, 3.5]) and convert it to integers using `astype()`. What happens to the decimal parts?

**Multi-dimensional arrays:**

9. Create a 1D array with values [0, 1, 2, ..., 11] and reshape it into a 3×4 matrix.

10. Create a 2×3 matrix of random integers between 1 and 10.

11. Create a 3×3 matrix of ones and a 3×3 matrix of zeros, then concatenate them horizontally to form a 3×6 matrix.

Try completing these tasks on your own. If you get stuck, don't hesitate to refer back to the examples or check the NumPy documentation.

[⬆️ Back to the Top](#ue4-numpy)

---

## **Chapter 2.2:** Array Attributes

### 🔍 Shape and Size

Understanding an array's shape and size is fundamental to working effectively with NumPy. These attributes tell you about the structure and dimensions of your data, which is essential for proper analysis and manipulation.

### 🧩 Important Components

* **shape**: A tuple that gives the size of the array along each dimension
* **size**: The total number of elements in the array
* **ndim**: The number of dimensions (also called axes) of the array
* **itemsize**: The size in bytes of each array element
* **nbytes**: The total size in bytes of the array

| Attribute | Description | Example | Result |
|-----------|-------------|---------|--------|
| `shape` | Size in each dimension | `array([1, 2, 3]).shape` | `(3,)` |
| `size` | Total number of elements | `array([[1, 2], [3, 4]]).size` | `4` |
| `ndim` | Number of dimensions | `array([[1, 2], [3, 4]]).ndim` | `2` |
| `itemsize` | Bytes per element | `array([1, 2], dtype=np.int64).itemsize` | `8` |
| `nbytes` | Total bytes | `array([1, 2], dtype=np.int64).nbytes` | `16` |

### 📘 Main Content

#### Understanding Array Shape

The `shape` attribute is a tuple that describes the size of each dimension in the array. For example:


In [ ]:
import numpy as np

# 1D array (vector)
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector shape: {vector.shape}")  # Output: (5,)

# 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix shape: {matrix.shape}")  # Output: (2, 3)

# 3D array (tensor)
tensor = np.zeros((2, 3, 4))
print(f"Tensor shape: {tensor.shape}")  # Output: (2, 3, 4)


For a 2D array (matrix), the shape tuple `(rows, columns)` tells you the number of rows and columns. For higher-dimensional arrays, each position in the shape tuple corresponds to the size of that dimension.

You can also use the shape to calculate the total number of elements in the array:


In [ ]:
# Calculate number of elements from shape
matrix = np.zeros((3, 4))
num_elements = matrix.shape[0] * matrix.shape[1]  # 3 * 4 = 12
print(f"Number of elements: {num_elements}")


#### Working with Array Size

The `size` attribute gives you the total number of elements in the array, regardless of its shape:


In [ ]:
# Get the total number of elements
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector size: {vector.size}")  # Output: 5

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix size: {matrix.size}")  # Output: 6

tensor = np.zeros((2, 3, 4))
print(f"Tensor size: {tensor.size}")  # Output: 24


The relationship between `shape` and `size` is: `size` = product of all shape components.

#### Memory Usage of Arrays

NumPy provides attributes to determine how much memory an array uses:


In [ ]:
# Memory usage information
array_int32 = np.array([1, 2, 3, 4], dtype=np.int32)
array_float64 = np.array([1, 2, 3, 4], dtype=np.float64)

print(f"Int32 itemsize: {array_int32.itemsize} bytes")  # Output: 4 bytes
print(f"Float64 itemsize: {array_float64.itemsize} bytes")  # Output: 8 bytes

print(f"Int32 array total bytes: {array_int32.nbytes}")  # Output: 16 bytes
print(f"Float64 array total bytes: {array_float64.nbytes}")  # Output: 32 bytes


The `itemsize` is the number of bytes used for each element, which depends on the data type. The `nbytes` is the total number of bytes used by the array, calculated as `itemsize * size`.

Understanding memory usage is particularly important when working with large datasets, as it can help you optimize your code and prevent memory-related issues.

#### Using Array Attributes in Practice

Array attributes can be particularly useful when:

1. **Validating input data**: Checking if an array has the expected shape
2. **Memory optimization**: Knowing how much memory your arrays use
3. **Algorithm development**: Designing operations that work with different array shapes
4. **Debugging**: Identifying shape mismatches or unexpected dimensions

For example, before performing a matrix multiplication, you might want to verify that the input matrices have compatible shapes:


In [ ]:
def matrix_multiply(a, b):
    # Check if matrices have compatible shapes for multiplication
    if a.shape[1] != b.shape[0]:
        raise ValueError(f"Incompatible shapes: {a.shape} and {b.shape}")
    # Proceed with multiplication...
    return np.dot(a, b)


#### ⚠️ Common Mistakes with Array Attributes

* **Confusing shape indices**: Remember that for a 2D array, `shape[0]` is rows and `shape[1]` is columns.
* **Overlooking tuple unpacking**: You can unpack the shape tuple: `rows, cols = matrix.shape`.
* **Forgetting that shape is a tuple**: This can cause issues when you try to modify it directly.

#### 🔄 Quick Check: Array Attributes

What is the `ndim` and `size` of the array created by `np.zeros((3, 4, 2))`?

<details>
   <summary>View Answer</summary>

   ```
   ndim = 3 (three dimensions)
   size = 24 (3 * 4 * 2 = 24 elements)
   ```

   This array is a 3-dimensional tensor with shape (3, 4, 2), containing 24 elements in total.
</details>

### 🔍 Data Type Information

NumPy arrays have a fixed data type (`dtype`) for all elements, which enables efficient memory usage and optimized operations. Understanding and manipulating data types is crucial for performance and correctness in numerical computing.

#### Checking Array Data Types


In [ ]:
import numpy as np

# Create arrays with different data types
int_array = np.array([1, 2, 3])
float_array = np.array([1.0, 2.0, 3.0])
bool_array = np.array([True, False, True])

# Check data types
print(f"Integer array dtype: {int_array.dtype}")  # Likely int64
print(f"Float array dtype: {float_array.dtype}")  # Likely float64
print(f"Boolean array dtype: {bool_array.dtype}")  # bool


#### Specifying Data Types

You can explicitly specify the data type when creating an array:


In [ ]:
# Create arrays with specific data types
uint8_array = np.array([1, 2, 3], dtype=np.uint8)
float32_array = np.array([1.0, 2.0, 3.0], dtype=np.float32)

print(f"uint8 array dtype: {uint8_array.dtype}")  # uint8
print(f"float32 array dtype: {float32_array.dtype}")  # float32


Common NumPy data types include:

| Data Type | Description | Range (typical) | Size (bytes) |
|-----------|-------------|-----------------|--------------|
| `bool_` | Boolean (True/False) | True or False | 1 |
| `int8` | 8-bit signed integer | -128 to 127 | 1 |
| `uint8` | 8-bit unsigned integer | 0 to 255 | 1 |
| `int16` | 16-bit signed integer | -32,768 to 32,767 | 2 |
| `uint16` | 16-bit unsigned integer | 0 to 65,535 | 2 |
| `int32` | 32-bit signed integer | -2³¹ to 2³¹-1 | 4 |
| `uint32` | 32-bit unsigned integer | 0 to 2³²-1 | 4 |
| `int64` | 64-bit signed integer | -2⁶³ to 2⁶³-1 | 8 |
| `uint64` | 64-bit unsigned integer | 0 to 2⁶⁴-1 | 8 |
| `float16` | 16-bit floating-point | ~±6.55×10⁴ | 2 |
| `float32` | 32-bit floating-point | ~±3.4×10³⁸ | 4 |
| `float64` | 64-bit floating-point | ~±1.8×10³⁰⁸ | 8 |
| `complex64` | Complex, two float32 | N/A | 8 |
| `complex128` | Complex, two float64 | N/A | 16 |

#### Converting Between Data Types

You can convert an array from one data type to another using the `astype()` method:


In [ ]:
# Convert between data types
float_array = np.array([1.5, 2.7, 3.9])
int_array = float_array.astype(np.int64)

print(float_array)  # [1.5 2.7 3.9]
print(int_array)    # [1 2 3] (truncated, not rounded)


Be aware that converting to a data type with less precision or range can lead to information loss or overflow:


In [ ]:
# Potential issues with data type conversion
large_values = np.array([1000, 2000, 3000])
small_type = large_values.astype(np.uint8)  # uint8 can only represent 0-255

print(large_values)  # [1000 2000 3000]
print(small_type)    # [232 208 184] (overflow - incorrect values!)


#### ⚠️ Common Mistakes with Data Types

* **Assuming default types**: NumPy might choose different default types depending on your system and NumPy version.
* **Ignoring precision issues**: Float operations can accumulate rounding errors, which can be significant for certain applications.
* **Overlooking type promotion**: When operating on arrays with different types, NumPy promotes types according to specific rules.

#### 🔄 Quick Check: Data Types

What will be the output of the following code?


In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int8)
b = a.astype(np.float32)
c = np.array([256, 257, 258], dtype=np.uint8)

print(a.dtype, a.itemsize)
print(b.dtype, b.itemsize)
print(c)


<details>
   <summary>View Answer</summary>

   Output:
   ```
   int8 1
   float32 4
   [0 1 2]
   ```

   Explanation:
   - `a` has data type `int8` which uses 1 byte per element
   - `b` has data type `float32` which uses 4 bytes per element
   - `c` shows overflow: in `uint8` (8-bit unsigned integers), values can only be from 0 to 255. When 256 is stored, it wraps around to 0, 257 becomes 1, and 258 becomes 2.
</details>

### 🔍 Dimensionality

The dimensionality of a NumPy array, accessed through the `ndim` attribute, tells you how many axes (dimensions) the array has. Understanding dimensionality is crucial for properly manipulating and analyzing array data.

#### Understanding Array Dimensions


In [ ]:
import numpy as np

# Create arrays with different dimensions
scalar = np.array(42)                                # 0D - scalar
vector = np.array([1, 2, 3])                         # 1D - vector
matrix = np.array([[1, 2, 3], [4, 5, 6]])            # 2D - matrix
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D - tensor

# Check the number of dimensions (ndim)
print(f"Scalar ndim: {scalar.ndim}")   # 0
print(f"Vector ndim: {vector.ndim}")   # 1
print(f"Matrix ndim: {matrix.ndim}")   # 2
print(f"Tensor ndim: {tensor.ndim}")   # 3


Each dimension corresponds to a level of nested lists in the array's creation, or to an axis in the resulting data structure:

- **0D**: A single value (scalar)
- **1D**: A sequence of values (vector)
- **2D**: A table of values (matrix)
- **3D**: A cube of values (tensor)
- **Higher dimensions**: More complex structures (hypercubes)

#### Adding and Removing Dimensions

NumPy provides several ways to add or remove dimensions:


In [ ]:
# Adding a new axis (dimension)
vector = np.array([1, 2, 3])  # 1D: shape (3,)
column_vector = vector[:, np.newaxis]  # 2D: shape (3, 1)
row_vector = vector[np.newaxis, :]     # 2D: shape (1, 3)

print(f"Original vector shape: {vector.shape}")       # (3,)
print(f"Column vector shape: {column_vector.shape}")  # (3, 1)
print(f"Row vector shape: {row_vector.shape}")        # (1, 3)


The `np.newaxis` (or `None`) is a special index that adds a new dimension of length 1. This is particularly useful for broadcasting or when working with functions that expect a specific dimensionality.

You can also use the `reshape` method to add or remove dimensions:


In [ ]:
# Reshape to add dimensions
vector = np.array([1, 2, 3, 4])           # 1D: shape (4,)
matrix = vector.reshape(2, 2)             # 2D: shape (2, 2)
tensor = vector.reshape(2, 2, 1)          # 3D: shape (2, 2, 1)

print(f"Vector: {vector.shape}, ndim: {vector.ndim}")  # (4,), 1
print(f"Matrix: {matrix.shape}, ndim: {matrix.ndim}")  # (2, 2), 2
print(f"Tensor: {tensor.shape}, ndim: {tensor.ndim}")  # (2, 2, 1), 3


To remove dimensions of size 1 (often called "squeezing"), you can use the `squeeze` method:


In [ ]:
# Removing dimensions of size 1
expanded = np.array([[[1], [2]]])           # 3D: shape (1, 2, 1)
squeezed = expanded.squeeze()               # 1D: shape (2,)

print(f"Expanded shape: {expanded.shape}")   # (1, 2, 1)
print(f"Squeezed shape: {squeezed.shape}")   # (2,)


#### Practical Applications of Dimensionality

Understanding and manipulating array dimensions is essential for:

1. **Compatibility with functions**: Many NumPy and scientific Python functions expect specific dimensionality.
2. **Broadcasting**: Adding dimensions enables broadcasting operations between arrays of different shapes.
3. **Matrix operations**: Proper dimensionality is required for linear algebra operations.
4. **Data analysis**: Different dimensions might represent different aspects of your data (samples, features, time points, etc.).

#### ⚠️ Common Mistakes with Dimensionality

* **Confusion between shape and ndim**: Remember that `ndim` is the length of the `shape` tuple.
* **Incorrect reshaping**: The total number of elements must remain the same when reshaping.
* **Forgetting that scalars are 0D**: A single value in NumPy is a 0-dimensional array, not a 1-dimensional array of length 1.

#### 🔄 Quick Check: Dimensionality

What will be the shape and ndim of the result of the following operation?


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
result = a + b


<details>
   <summary>View Answer</summary>

   The result will have shape `(3, 3)` and `ndim = 2`.

   This is because:
   - `a` has shape `(3,)` and `ndim = 1`
   - `b` has shape `(3, 1)` and `ndim = 2`
   - When adding them, broadcasting rules apply: `a` is treated as a row vector and `b` as a column vector, resulting in a 3×3 matrix.
</details>

#### 📚 Further Reading: Array Attributes

* [NumPy Array Attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes) - Official documentation
* [Data Type Objects in NumPy](https://numpy.org/doc/stable/reference/arrays.dtypes.html) - Detailed information on data types
* [Broadcasting in NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html) - How array shapes interact in operations

---

## 👨‍💻 **Practice Tasks 2.2:** Working with Array Attributes

Now let's practice examining and manipulating array attributes:

**Shape and size exploration:**

1. Create a 3×4 array of random integers and examine its shape, size, and ndim.

2. Create a 2×3×4 array of zeros and calculate how many elements it contains using the shape attribute.

3. Create an array with shape (5, 5) and print its total size in bytes.

**Data type manipulation:**

4. Create an array of integers and check its data type and itemsize.

5. Create the same array with float32 data type and compare its memory usage (nbytes) with the integer array.

6. Create an array of values that exceed the range of np.uint8 (0-255), convert it to uint8, and observe what happens.

**Dimensionality operations:**

7. Create a 1D array and convert it to a column vector by adding a new axis.

8. Create a 3×4 array and reshape it to a 2×6 array without changing the data.

9. Create a 3D array with shape (2, 1, 3) and use the squeeze method to remove dimensions of size 1.

10. Create two arrays, one with shape (3,) and another with shape (3, 1), then add them together and observe the shape of the result (broadcasting).

Try completing these tasks on your own. Examining and manipulating array attributes is fundamental to effective NumPy programming.

[⬆️ Back to the Top](#ue4-numpy)

---

## **Chapter 2.3:** Indexing Techniques

### 🔍 Basic Indexing

Indexing is the process of accessing specific elements in a NumPy array. NumPy provides powerful indexing techniques that allow you to efficiently retrieve and manipulate data in arrays of any dimension.

### 🧩 Important Components

* **Zero-based indexing**: Array indices start from 0 (first element) and go up to n-1 (last element) for a dimension of size n
* **Negative indexing**: Negative indices count from the end of the array (-1 is the last element)
* **Multi-dimensional indexing**: Using commas to separate indices for each dimension
* **Integer indexing**: Using integer indices to access individual elements
* **View vs. copy**: Understanding when indexing returns a view (reference) versus a copy of the data

| Indexing Type | Description | Example | Result |
|---------------|-------------|---------|--------|
| Basic positive | Access by position | `arr[0]` | First element |
| Basic negative | Count from end | `arr[-1]` | Last element |
| Multi-dimensional | Multiple indices | `arr[1, 2]` | Element at row 1, col 2 |

### 📘 Main Content

#### One-Dimensional Array Indexing

For a 1D array (vector), indexing works similarly to Python lists:


In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Positive indexing (0-based)
print(arr[0])   # Output: 10 (first element)
print(arr[2])   # Output: 30 (third element)

# Negative indexing (counting from the end)
print(arr[-1])  # Output: 50 (last element)
print(arr[-2])  # Output: 40 (second-to-last element)


#### Multi-Dimensional Array Indexing

For multi-dimensional arrays, you need to specify an index for each dimension, separated by commas:


In [ ]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements in a 2D array
print(matrix[0, 0])  # Output: 1 (first row, first column)
print(matrix[1, 2])  # Output: 6 (second row, third column)
print(matrix[2, -1])  # Output: 9 (third row, last column)

# Create a 3D array (tensor)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Accessing elements in a 3D array
print(tensor[0, 0, 0])  # Output: 1 (first layer, first row, first column)
print(tensor[1, 1, 1])  # Output: 8 (second layer, second row, second column)


Note that `matrix[1, 2]` is equivalent to `matrix[1][2]`, but the comma notation is more efficient and is the preferred style in NumPy.

#### Modifying Elements with Indexing

You can use indexing to modify array elements:


In [ ]:
# Modify elements in arrays
arr = np.array([10, 20, 30, 40, 50])
arr[2] = 35  # Change the third element
print(arr)  # Output: [10 20 35 40 50]

matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix[0, 1] = 20  # Change element at first row, second column
print(matrix)
# Output:
# [[ 1 20  3]
#  [ 4  5  6]]


#### Indexing Subarrays

When indexing a multi-dimensional array with fewer indices than dimensions, you get a subarray:


In [ ]:
# Indexing subarrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get an entire row
row1 = matrix[1]  # Second row
print(row1)  # Output: [4 5 6]

# 3D array example
tensor = np.zeros((2, 3, 4))  # 2 layers, 3 rows, 4 columns

# Get one layer (2D subarray)
layer = tensor[0]  # First layer
print(layer.shape)  # Output: (3, 4)

# Get one row from one layer (1D subarray)
row = tensor[0, 1]  # First layer, second row
print(row.shape)  # Output: (4,)


#### Understanding Views vs. Copies

An important concept in NumPy indexing is the distinction between views and copies:

- A **view** is a way of accessing array data that doesn't copy the data. Changes to the view affect the original array.
- A **copy** is a new array with its own data that doesn't affect the original array when modified.

Basic indexing in NumPy returns views, not copies:


In [ ]:
# Views vs. copies
arr = np.array([1, 2, 3, 4, 5])

# Basic indexing returns a view
view = arr[1:4]  # Get elements at indices 1, 2, 3
view[0] = 20     # Modify the first element of the view

print(view)      # Output: [20  3  4]
print(arr)       # Output: [ 1 20  3  4  5] (original array is modified!)

# Create an explicit copy
copy_arr = arr.copy()
copy_arr[0] = 100  # Modify the copy

print(copy_arr)  # Output: [100  20   3   4   5]
print(arr)       # Output: [  1  20   3   4   5] (original array is unchanged)


This behavior is important to understand because it can lead to unexpected results if you're not aware of it. It's also a feature that can be used to efficiently modify large arrays without creating unnecessary copies.

#### ⚠️ Common Mistakes with Basic Indexing

* **Index out of bounds**: Using an index >= the size of the dimension causes an `IndexError`.
* **Wrong dimensionality**: Not providing enough indices for all dimensions you want to specify.
* **Unintentional views**: Modifying what you thought was a copy but is actually a view of the original array.

#### 🔄 Quick Check: Basic Indexing

Given the following 3×3 matrix, what will be the value of `result`?


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = matrix[1, 1]
row = matrix[2]
result = element + row[0]


<details>
   <summary>View Answer</summary>

   ```
   result = 12
   ```

   Explanation:
   - `matrix[1, 1]` gives the element at the second row, second column, which is 5
   - `matrix[2]` gives the third row, which is [7, 8, 9]
   - `row[0]` is the first element of the third row, which is 7
   - `result = 5 + 7 = 12`
</details>

### 🔍 Boolean Indexing

Boolean indexing is a powerful technique that allows you to select elements from an array based on conditions. It uses arrays of boolean values (True/False) to determine which elements to select.

#### Using Comparison Operators for Boolean Indexing

You can create boolean arrays using comparison operators:


In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean array using a condition
bool_arr = arr > 5
print(bool_arr)  # Output: [False False False False False  True  True  True  True  True]

# Use the boolean array to index the original array
filtered = arr[bool_arr]
print(filtered)  # Output: [ 6  7  8  9 10]


You can simplify this by combining the steps:


In [ ]:
# Direct boolean indexing
filtered = arr[arr > 5]
print(filtered)  # Output: [ 6  7  8  9 10]


#### Combining Conditions

You can combine multiple conditions using logical operators (`&` for AND, `|` for OR, `~` for NOT):


In [ ]:
# Select elements that are greater than 3 AND less than 8
filtered = arr[(arr > 3) & (arr < 8)]
print(filtered)  # Output: [4 5 6 7]

# Select elements that are less than 3 OR greater than 8
filtered = arr[(arr < 3) | (arr > 8)]
print(filtered)  # Output: [1 2 9 10]

# Select elements that are NOT greater than 5
filtered = arr[~(arr > 5)]
print(filtered)  # Output: [1 2 3 4 5]


Note that you need to use parentheses around each condition when combining them with logical operators.

#### Boolean Indexing with Multi-dimensional Arrays

Boolean indexing works with multi-dimensional arrays too:


In [ ]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a boolean array from a condition
bool_matrix = matrix > 5
print(bool_matrix)
# Output:
# [[False False False]
#  [False False  True]
#  [ True  True  True]]

# Use boolean indexing on 2D array
filtered = matrix[bool_matrix]
print(filtered)  # Output: [6 7 8 9]


Notice that the result is a 1D array containing all elements that satisfy the condition, regardless of their position in the original array.

#### Setting Values with Boolean Indexing

Boolean indexing can also be used to modify specific elements:


In [ ]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Set all elements greater than 3 to 10
arr[arr > 3] = 10
print(arr)  # Output: [ 1  2  3 10 10]

# 2D example
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix[matrix % 2 == 0] = 0  # Set all even numbers to 0
print(matrix)
# Output:
# [[1 0 3]
#  [0 5 0]
#  [7 0 9]]


#### ⚠️ Common Mistakes with Boolean Indexing

* **Using `and`/`or` instead of `&`/`|`**: Python's logical operators don't work element-wise with NumPy arrays.
* **Forgetting parentheses**: When combining conditions, each condition needs to be in parentheses.
* **Assignment shape mismatch**: When assigning values using boolean indexing, the shape of the values must be broadcastable to the shape of the selected elements.

#### 🔄 Quick Check: Boolean Indexing

What will be the output of the following code?


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = (arr > 3) & (arr < 8)
arr[mask] = 0
print(arr)


<details>
   <summary>View Answer</summary>

   ```
   [1 2 3 0 0 0 0 8 9]
   ```

   Explanation:
   - The mask is `True` for elements that are greater than 3 AND less than 8 (elements at indices 3, 4, 5, 6)
   - These elements (4, 5, 6, 7) are replaced with 0
   - The other elements (1, 2, 3, 8, 9) remain unchanged
</details>

### 🔍 Fancy Indexing

Fancy indexing is a term used for indexing NumPy arrays with arrays of indices. Instead of using a boolean mask or a single index, you use arrays of integers to specify the positions of the elements you want to select.

#### Indexing with Integer Arrays

You can use an array of integers to select multiple elements from an array:


In [ ]:
import numpy as np

# Create an array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Select specific elements by index
indices = np.array([1, 3, 5, 7])
selected = arr[indices]
print(selected)  # Output: [20 40 60 80]


You can also use a list of indices, though NumPy arrays are more efficient for large datasets:


In [ ]:
# Using a list for indexing
selected = arr[[0, 2, 4, 8]]
print(selected)  # Output: [10 30 50 90]


#### Changing the Order of Elements

Fancy indexing allows you to rearrange elements in any order:


In [ ]:
# Reverse the array using fancy indexing
indices = np.arange(len(arr) - 1, -1, -1)
reversed_arr = arr[indices]
print(reversed_arr)  # Output: [90 80 70 60 50 40 30 20 10]

# Shuffle the array
np.random.seed(42)  # For reproducibility
indices = np.random.permutation(len(arr))
shuffled = arr[indices]
print(shuffled)  # Output: [50 20 70 10 60 90 30 80 40] (or similar)


#### Fancy Indexing with Multi-dimensional Arrays

Fancy indexing works with multi-dimensional arrays in two ways:

1. **Using arrays of indices for each dimension**:


In [ ]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select specific rows and columns
rows = np.array([0, 2])
cols = np.array([0, 2])
selected = matrix[rows, cols]
print(selected)  # Output: [1 9]


This selects the elements at positions (0,0) and (2,2).

2. **Using a single array for one dimension**:


In [ ]:
# Select specific rows
rows = np.array([0, 2])
selected_rows = matrix[rows]
print(selected_rows)
# Output:
# [[1 2 3]
#  [7 8 9]]

# Select specific columns
cols = np.array([0, 2])
selected_cols = matrix[:, cols]
print(selected_cols)
# Output:
# [[1 3]
#  [4 6]
#  [7 9]]


#### Combining Fancy Indexing with Other Techniques

You can combine fancy indexing with other indexing techniques:


In [ ]:
# Combine fancy indexing with slicing
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
rows = np.array([0, 2])
selected = matrix[rows, 1:3]
print(selected)
# Output:
# [[ 2  3]
#  [10 11]]

# Combine fancy indexing with boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = arr > 5
indices = np.array([0, 2, 4, 6, 8])
selected = arr[mask][indices]  # Select elements > 5, then take indices [0,2,4]
print(selected)  # Output: [6 8]


#### Modifying with Fancy Indexing

You can use fancy indexing to modify specific elements:


In [ ]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Modify specific elements
indices = np.array([0, 2, 4])
arr[indices] = 10
print(arr)  # Output: [10  2 10  4 10]

# 2D example
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([0, 2])
matrix[rows, cols] = 100
print(matrix)
# Output:
# [[100   2   3]
#  [  4   5   6]
#  [  7   8 100]]


#### ⚠️ Common Mistakes with Fancy Indexing

* **Unexpected behavior with repeated indices**: Using the same index multiple times is allowed and will select the same element multiple times.
* **View vs. copy confusion**: Unlike basic slicing, fancy indexing always returns a copy, not a view.
* **Index out of bounds**: Using indices that are outside the valid range causes an `IndexError`.

#### 🔄 Quick Check: Fancy Indexing

What will be the output of the following code?


In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 0, 2])
cols = np.array([0, 1, 2])
result = matrix[rows, cols]
print(result)


<details>
   <summary>View Answer</summary>

   ```
   [1 2 9]
   ```

   Explanation:
   This selects elements at positions:
   - (0, 0) which is 1
   - (0, 1) which is 2
   - (2, 2) which is 9

   The result is a 1D array containing these three values.
</details>

#### 📚 Further Reading: Indexing Techniques

* [NumPy Array Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html) - Official documentation
* [Boolean Indexing with NumPy](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing) - Detailed guide
* [Fancy Indexing with NumPy](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) - Official explanation

---

## 👨‍💻 **Practice Tasks 2.3:** Using Indexing Techniques

Now let's practice different indexing techniques on NumPy arrays:

**Basic indexing:**

1. Create a 1D array with values from 0 to 9 and:
   - Access the first element
   - Access the last element using negative indexing
   - Access the middle element

2. Create a 3×4 matrix of sequential numbers (0-11) and:
   - Access the element at the second row, third column
   - Access the last element in the first row
   - Access the entire second row

**Boolean indexing:**

3. Create an array of 10 random integers between 0 and 100 and:
   - Find all elements greater than 50
   - Find all even numbers
   - Find all elements that are both greater than 30 and less than 70

4. Create a 5×5 matrix of random integers between 0 and 10 and:
   - Replace all odd numbers with -1
   - Set all elements greater than 7 to 999
   - Find the number of elements that are either less than 3 or greater than 8

**Fancy indexing:**

5. Create an array of values from 10 to 90 (step 10) and:
   - Extract elements at indices 0, 2, 4, 6
   - Reverse the array using fancy indexing
   - Create a new array that repeats the first and last elements

6. Create a 4×4 matrix of sequential numbers and:
   - Extract elements at positions (0,0), (1,1), (2,2), and (3,3) (the diagonal)
   - Extract the first and last row
   - Extract a submatrix containing elements from the first and third rows and the second and fourth columns

7. Combine indexing techniques by creating a 5×5 matrix and:
   - Extract all elements greater than the mean value
   - Extract all even elements from the diagonal
   - Set all elements less than the median to zero

Try completing these tasks on your own. Mastering indexing techniques is crucial for efficient data manipulation in NumPy.

[⬆️ Back to the Top](#ue4-numpy)

---

## **Chapter 2.4:** Slicing Techniques

### 🔍 Basic Slicing

Slicing in NumPy allows you to extract parts of an array along each dimension. It's a powerful way to select entire rows, columns, or more complex subarrays without having to specify each element individually.

### 🧩 Important Components

* **Slice syntax**: `start:stop:step` where all parameters are optional
* **Default values**: start=0, stop=dimension size, step=1
* **Negative indices**: Count from the end of the array
* **View vs. copy**: Slices create views, not copies, by default

| Slice | Description | Example | Result |
|-------|-------------|---------|--------|
| `start:stop` | Elements from index start up to but not including stop | `arr[1:4]` | Elements at indices 1, 2, 3 |
| `:stop` | Elements from beginning up to but not including stop | `arr[:3]` | Elements at indices 0, 1, 2 |
| `start:` | Elements from start to the end of the array | `arr[2:]` | Elements from index 2 to end |
| `::step` | Every step-th element of the array | `arr[::2]` | Every other element |
| `start:stop:step` | Elements from start up to stop, by step | `arr[1:7:2]` | Elements at indices 1, 3, 5 |

### 📘 Main Content

#### Basic Slice Syntax

The basic syntax for slicing is `array[start:stop:step]`, where:
- `start`: The index to start (inclusive)
- `stop`: The index to stop (exclusive)
- `step`: The step size between elements

Any of these parameters can be omitted, in which case default values are used:


In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic slicing with different parameters
print(arr[1:6])      # Output: [1 2 3 4 5] (start=1, stop=6, step=1)
print(arr[1:6:2])    # Output: [1 3 5] (start=1, stop=6, step=2)
print(arr[:5])       # Output: [0 1 2 3 4] (start=0, stop=5, step=1)
print(arr[5:])       # Output: [5 6 7 8 9] (start=5, stop=len(arr), step=1)
print(arr[::2])      # Output: [0 2 4 6 8] (start=0, stop=len(arr), step=2)
print(arr[:])        # Output: [0 1 2 3 4 5 6 7 8 9] (entire array)


#### Negative Indices and Steps

You can use negative indices and steps for more complex slicing patterns:


In [ ]:
# Negative indices count from the end
print(arr[-5:])      # Output: [5 6 7 8 9] (last 5 elements)
print(arr[:-2])      # Output: [0 1 2 3 4 5 6 7] (all but the last 2 elements)
print(arr[-8:-2])    # Output: [2 3 4 5 6 7] (from 8th-to-last to 2nd-to-last)

# Negative steps reverse the array
print(arr[::-1])     # Output: [9 8 7 6 5 4 3 2 1 0] (reversed array)
print(arr[5:1:-1])   # Output: [5 4 3 2] (from index 5 to index 2, backwards)
print(arr[::-2])     # Output: [9 7 5 3 1] (every other element, reversed)

#### Multi-dimensional Slicing

For multi-dimensional arrays, you can slice along each dimension by separating the slice expressions with commas:

# Create a 2D array (matrix)
matrix = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

# Slicing rows and columns
print(matrix[1:, :2])
# Output:
# [[4 5]
#  [8 9]]

# Taking specific row slices
print(matrix[::2, 1:3])
# Output:
# [[1 2]
#  [9 10]]

# Get the first two rows and alternate columns
print(matrix[:2, ::2])
# Output:
# [[0 2]
#  [4 6]]


You can combine slicing with regular indexing:


In [ ]:
# Mix of indexing and slicing
print(matrix[1, :])       # Output: [4 5 6 7] (second row)
print(matrix[:, 2])       # Output: [ 2  6 10] (third column)
print(matrix[-1, 1:3])    # Output: [ 9 10] (last row, columns 1 through 2)


#### Working with 3D and Higher Dimensional Arrays

Slicing extends naturally to higher dimensional arrays:


In [ ]:
# Create a 3D array
tensor = np.array([
    [[0, 1], [2, 3]],
    [[4, 5], [6, 7]],
    [[8, 9], [10, 11]]
])

# Slicing in 3D
print(tensor[1:, 0, :])  # Second and third matrices, first row, all columns
# Output:
# [[4 5]
#  [8 9]]

print(tensor[:, :, 1])   # All matrices, all rows, second column
# Output:
# [[ 1  3]
#  [ 5  7]
#  [ 9 11]]

# Complex 3D slicing
print(tensor[::2, :, ::2])  # First and third matrices, all rows, alternate columns
# Output:
# [[[ 0]
#   [ 2]]
#  [[ 8]
#   [10]]]


#### Views vs. Copies in Slicing

An important concept in NumPy slicing is that slices return views, not copies, by default. This means that modifying the slice will modify the original array:


In [ ]:
# Create an array
arr = np.array([0, 1, 2, 3, 4, 5])

# Create a slice (view)
slice_view = arr[1:4]  # [1 2 3]

# Modify the slice
slice_view[0] = 100

# The original array is modified!
print(arr)  # Output: [  0 100   2   3   4   5]


If you want to create a copy instead of a view, use the `copy()` method:


In [ ]:
# Create an array
arr = np.array([0, 1, 2, 3, 4, 5])

# Create a slice copy
slice_copy = arr[1:4].copy()  # [1 2 3]

# Modify the copy
slice_copy[0] = 100

# The original array is NOT modified
print(arr)       # Output: [0 1 2 3 4 5]
print(slice_copy)  # Output: [100 2 3]


#### ⚠️ Common Mistakes with Slicing

* **Off-by-one errors**: Forgetting that the `stop` index is exclusive (not inclusive) can lead to incorrect results.
* **Unintended modifications**: Modifying a slice also modifies the original array, which might lead to unexpected side effects.
* **Wrong dimensions**: When slicing multi-dimensional arrays, it's important to provide the correct number of slice expressions.

#### 🔄 Quick Check: Slicing

What will be the output of the following code?


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice1 = arr[2:7:2]
slice2 = arr[::-2]

print(slice1)
print(slice2)


<details>
   <summary>View Answer</summary>

   ```
   [2 4 6]
   [9 7 5 3 1]
   ```

   Explanation:
   - `slice1` starts at index 2, ends before index 7, with a step of 2, so it includes elements at indices 2, 4, and 6
   - `slice2` includes the entire array with a step of -2 (meaning every second element, going backwards), so it starts with the last element and works backward
</details>

### 🔍 Multi-dimensional Slicing

Multi-dimensional slicing allows you to extract subsets from arrays with multiple dimensions, enabling you to work with specific rows, columns, or more complex subsets of your data.

#### Slicing in Different Dimensions

For a 2D array (matrix), the first dimension typically represents rows and the second dimension represents columns:


In [ ]:
import numpy as np

# Create a 3x4 matrix
matrix = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

# Extract specific rows
first_row = matrix[0, :]        # First row (same as matrix[0])
last_row = matrix[-1, :]        # Last row (same as matrix[-1])
alternate_rows = matrix[::2, :] # First and third rows (same as matrix[::2])

print("First row:", first_row)
print("Last row:", last_row)
print("Alternate rows:")
print(alternate_rows)

# Extract specific columns
first_col = matrix[:, 0]        # First column
last_col = matrix[:, -1]        # Last column
alternate_cols = matrix[:, ::2] # First and third columns

print("First column:", first_col)
print("Last column:", last_col)
print("Alternate columns:")
print(alternate_cols)


#### Extracting Subarrays

You can extract specific rectangular regions from multi-dimensional arrays:


In [ ]:
# Extract the 2x2 top-left corner
top_left = matrix[:2, :2]
print("Top-left corner:")
print(top_left)
# Output:
# [[0 1]
#  [4 5]]

# Extract the 2x2 bottom-right corner
bottom_right = matrix[1:, 2:]
print("Bottom-right corner:")
print(bottom_right)
# Output:
# [[ 6  7]
#  [10 11]]

# Extract a 2x3 subarray from the middle
middle = matrix[0:2, 1:4]
print("Middle section:")
print(middle)
# Output:
# [[1 2 3]
#  [5 6 7]]


#### Slicing with Ellipsis (`...`)

For arrays with many dimensions, the ellipsis (`...`) notation is useful to avoid having to explicitly specify slices for all dimensions:


In [ ]:
# Create a 4D array
array_4d = np.zeros((2, 3, 4, 5))

# Select the first element along the first axis, and all elements along the remaining axes
subset = array_4d[0, ...]
print(subset.shape)  # Output: (3, 4, 5)

# Equivalent to:
subset = array_4d[0, :, :, :]
print(subset.shape)  # Output: (3, 4, 5)

# Select specific elements in the first and last dimensions
subset = array_4d[0, ..., 2]
print(subset.shape)  # Output: (3, 4)

# Equivalent to:
subset = array_4d[0, :, :, 2]
print(subset.shape)  # Output: (3, 4)


The ellipsis notation is particularly useful when you're not sure how many dimensions an array has, or when you only care about specific dimensions.

#### Modifying Subarrays

Just like with 1D arrays, slices of multi-dimensional arrays are views by default:


In [ ]:
# Create a 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Extract a 2x2 subarray (view)
subarray = matrix[:2, :2]
print("Original subarray:")
print(subarray)
# Output:
# [[1 2]
#  [4 5]]

# Modify the subarray
subarray[0, 0] = 100

# The original matrix is also modified
print("Modified matrix:")
print(matrix)
# Output:
# [[100   2   3]
#  [  4   5   6]
#  [  7   8   9]]


#### ⚠️ Common Mistakes with Multi-dimensional Slicing

* **Dimension confusion**: Mixing up which dimension corresponds to rows vs. columns in a 2D array.
* **Shape misunderstandings**: Not fully grasping the shape of the resulting subarray after slicing.
* **Missing dimensions**: When using the `:` notation, forgetting to include all dimensions of the array.

#### 🔄 Quick Check: Multi-dimensional Slicing

Given the following 3×4 matrix, what will be the shape and content of the resulting array?


In [ ]:
matrix = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

result = matrix[1:, ::2]


<details>
   <summary>View Answer</summary>

   The shape will be (2, 2) and the content will be:
   ```
   [[ 4  6]
    [ 8 10]]
   ```

   Explanation:
   - `matrix[1:, ::2]` selects rows from index 1 to the end (second and third rows) and columns at indices 0 and 2 (first and third columns)
   - This results in a 2×2 matrix containing the elements at positions (1,0), (1,2), (2,0), and (2,2) from the original matrix
</details>

### 🔍 Views vs. Copies

Understanding the difference between views and copies is essential for efficient memory usage and avoiding unexpected behavior when working with NumPy arrays.

#### What are Views and Copies?

* **View**: A view is an array that shares memory with another array. Any changes to the view are reflected in the original array and vice versa.
* **Copy**: A copy is an independent array with its own memory. Changes to the copy do not affect the original array.


In [ ]:
import numpy as np

# Create an original array
original = np.array([1, 2, 3, 4, 5])

# Creating a view
view = original[1:4]  # This is a view of original[1], original[2], and original[3]

# Creating a copy
copy = original[1:4].copy()  # This is a copy of the values

# Show the initial values
print("Original:", original)  # [1 2 3 4 5]
print("View:", view)          # [2 3 4]
print("Copy:", copy)          # [2 3 4]

# Modify the view
view[0] = 100

# Check the effect
print("After modifying view:")
print("Original:", original)  # [1 100 3 4 5] - original is affected by view modification
print("View:", view)          # [100 3 4]

# Modify the copy
copy[0] = 200

# Check the effect
print("After modifying copy:")
print("Original:", original)  # [1 100 3 4 5] - original is not affected by copy modification
print("Copy:", copy)          # [200 3 4]


#### Operations that Return Views

The following operations typically return views:

1. **Simple slicing**: `arr[1:5]`, `arr[:, 2]`, etc.
2. **Reshaping without size change**: `arr.reshape(3, 4)` (if possible without copying)
3. **Transposing**: `arr.T` or `arr.transpose()`
4. **Changing data type without size change**: `arr.view(dtype)`


In [ ]:
# Demonstrate operations that create views
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping that returns a view
reshaped = arr.reshape(2, 3)
reshaped[0, 0] = 100
print("Original after reshape modification:", arr)  # [100 2 3 4 5 6]

# Transposing returns a view
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed = matrix.T
transposed[0, 0] = 100
print("Original after transpose modification:")
print(matrix)  # [[100 2 3], [4 5 6]]


#### Operations that Return Copies

The following operations typically return copies:

1. **Fancy indexing**: `arr[[0, 2, 4]]`
2. **Boolean indexing**: `arr[arr > 5]`
3. **Explicit copying**: `arr.copy()`
4. **Type conversions that change size**: `arr.astype(np.float64)` when arr is originally int32
5. **Most arithmetic operations**: `arr + 5`, `arr * 2`, etc.


In [ ]:
# Demonstrate operations that create copies
arr = np.array([1, 2, 3, 4, 5, 6])

# Fancy indexing creates a copy
fancy = arr[[0, 2, 4]]
fancy[0] = 100
print("Original after fancy modification:", arr)  # [1 2 3 4 5 6] - unchanged

# Boolean indexing creates a copy
boolean = arr[arr > 3]
boolean[0] = 100
print("Original after boolean modification:", arr)  # [1 2 3 4 5 6] - unchanged

# Arithmetic operations create copies
plus_five = arr + 5
plus_five[0] = 100
print("Original after arithmetic modification:", arr)  # [1 2 3 4 5 6] - unchanged


#### When to Use Views vs. Copies

Views and copies each have their appropriate use cases:

* **Use views when**:
    * You need to modify the original array through a subset or reshaping
    * Memory efficiency is critical
    * You're working with large arrays and want to avoid duplicating data

* **Use copies when**:
    * You need to ensure that modifications to the new array won't affect the original
    * You need to convert data to a different type
    * You're selecting non-contiguous parts of an array (fancy indexing)

#### Checking if an Array is a View or a Copy

NumPy doesn't provide a direct method to determine if an array is a view or a copy, but you can infer it by modifying one array and checking if the other is affected:


In [ ]:
def is_view(arr1, arr2):
    """Test if arr2 is a view of arr1"""
    old_value = arr2.flat[0]  # Save the original value
    arr2.flat[0] = 42  # Modify the first element of arr2

    is_view = arr1.flat[0] == 42  # Check if arr1 was modified

    # Restore the original value
    arr2.flat[0] = old_value

    return is_view

# Test with a view
a = np.array([1, 2, 3, 4])
b = a[1:3]
print("Is b a view of a?", is_view(a, b))  # True

# Test with a copy
c = a[1:3].copy()
print("Is c a view of a?", is_view(a, c))  # False


#### ⚠️ Common Mistakes with Views vs. Copies

* **Assuming slice is a copy**: This is a common mistake for those coming from Python lists, where slices create copies.
* **Overlooking unintended modifications**: Modifying a view will change the original array, which might lead to unexpected behavior.
* **Memory leaks**: Holding onto a small view of a large array can prevent the large array from being garbage-collected.

#### 🔄 Quick Check: Views vs. Copies

What will be the output of the following code?


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
c = a[[1, 2, 3]]

b[0] = 20
c[0] = 30

print(a)

<details>
   <summary>View Answer</summary>

   ```
   [ 1 20  3  4  5]
   ```

   Explanation:
   - `b` is a view of `a` created by slicing, so changing `b[0]` (which corresponds to `a[1]`) changes `a`
   - `c` is a copy of elements from `a` created by fancy indexing, so changing `c[0]` does not affect `a`
</details>

#### 📚 Further Reading: Slicing and Views/Copies

* [NumPy Slicing](https://numpy.org/doc/stable/reference/arrays.indexing.html#basic-slicing-and-indexing) - Official documentation
* [Memory Layout of NumPy Arrays](https://numpy.org/doc/stable/dev/internals.html#memory-layout-of-numpy-arrays) - Understanding memory management
* [Copies and Views in NumPy](https://numpy.org/doc/stable/user/basics.copies.html) - Detailed explanation

---

## 👨‍💻 **Practice Tasks 2.4:** Slicing Arrays and Understanding Views/Copies

Let's practice slicing NumPy arrays and understanding the difference between views and copies:

**Basic slicing:**

1. Create a 1D array from 0 to 19 and:
   - Extract elements from index 5 to 10
   - Extract every third element
   - Reverse the array using slicing

2. Create a 2D array with shape (5, 5) containing values from 0 to 24 and:
   - Extract the first two rows
   - Extract the last two columns
   - Extract a 3×3 subarray from the center

**Multi-dimensional slicing:**

3. Create a 3×4 matrix of random integers between 1 and 100 and:
   - Extract all even-indexed rows and odd-indexed columns
   - Extract the middle row and all columns
   - Create a subarray containing only the corners of the original matrix

4. Create a 3D array with shape (2, 3, 4) filled with sequential numbers and:
   - Extract the first "layer" (a 2D subarray)
   - Extract all layers but only the first row from each
   - Use the ellipsis notation to select the middle column from all layers and rows

**Views versus copies:**

5. Create an array and demonstrate that:
   - Basic slicing creates a view (by modifying the slice and checking the original)
   - Fancy indexing creates a copy (by modifying the result and checking the original)

6. Performance comparison:
   - Create a large array (e.g., 1,000,000 elements)
   - Time how long it takes to create a slice (view) versus a copy
   - Explain the difference in your observations

7. Advanced practice - chained operations:
   - Create a 4×4 matrix
   - Create a slice of it, then use fancy indexing on the slice
   - Determine whether the result is a view or a copy of the original matrix
   - Explain why this is the case

Try completing these tasks on your own. Understanding slicing and the difference between views and copies is crucial for efficient NumPy programming.

[⬆️ Back to the Top](#ue4-numpy)

---

## **Chapter 2.5:** Coding Challenge

### 🏆 Stress Analysis 1/3

#### **Background**

In engineering, particularly within materials science and structural engineering, understanding how stress is distributed throughout a material under external forces is crucial for ensuring the safety and durability of designs. In this coding challenge, we'll use NumPy to simulate and analyze the stress distribution in a metal pole.

#### **Objective**

We'll simulate the stress distribution in a metal pole subjected to various conditions. We'll analyze how the stress changes when we introduce defects, apply heat treatment to certain areas, and account for the effect of gravity. This challenge will give you practical experience applying NumPy array operations to a real-world engineering problem.

#### **Setup**

For visualization, we'll use a simple function that displays the metal pole as a heatmap using Matplotlib:

In [ ]:
from matplotlib import pyplot as plt

# Simple heatmap to visualize the array
def plot_pole(arr):
    plt.figure(figsize=(10, 3))
    plt.imshow(arr, cmap='viridis')
    plt.colorbar(label='Stress (MPa)')
    plt.title('Metal Pole Stress Distribution')
    plt.xlabel('Length')
    plt.ylabel('Width')
    plt.show()


#### **Step-by-Step Tasks**

**Step 1: Initialize the Stress Distribution**
* Create a 5×25 array to represent a metal pole with a uniform initial stress of 50 MPa.
* This represents the baseline stress state of the pole before any modifications.


In [ ]:
import numpy as np
from matplotlib import pyplot as plt

# Function to visualize the pole
def plot_pole(arr):
    plt.figure(figsize=(10, 3))
    plt.imshow(arr, cmap='viridis')
    plt.colorbar(label='Stress (MPa)')
    plt.title('Metal Pole Stress Distribution')
    plt.xlabel('Length')
    plt.ylabel('Width')
    plt.show()

# Step 1: Initialize the metal pole's stress distribution
# Your code here: Create a 5×25 array filled with 50


**Step 2: Simulate Material Errors**
* Introduce three specific material errors by setting stress values to 65 MPa at specific locations.
* These represent manufacturing defects or flaws in the material.
* Set the stress to 65 MPa at positions (3, 13), (1, 21), and (4, 2).


In [ ]:
# Step 2: Introduce material errors
# Your code here: Set stress at the specified locations to 65 MPa


**Step 3: Apply Heat Treatment**
* Apply a 15% stress reduction to simulate heat treatment along all outer edges of the pole.
* This includes the top edge (first row), bottom edge (last row), front edge (first column), and back edge (last column).
* Heat treatment helps relieve stress in these areas, making the structure more stable.


In [ ]:
# Step 3: Apply heat treatment to edges
# Your code here: Reduce stress by 15% at all edges


**Step 4: Apply a Linear Force for Gravity**
* Add the effect of gravity as a linearly increasing force from left to right.
* The gravity effect should be 0 MPa at the leftmost column and 12 MPa at the rightmost column.
* This simulates how gravity affects the pole when it's mounted horizontally.


In [ ]:
# Step 4: Model the effect of gravity
# Your code here: Add a linear gravity effect from 0 to 12 MPa


**Step 5: Return the Array Attributes**
* Report the shape, size, and data type of the final stress distribution array.
* This gives us important information about the structure of our data.


In [ ]:
# Step 5: Report array attributes
# Your code here: Print shape, size, and data type

#### **Expected Output**

After completing all steps, you should have a stress distribution that:
1. Started with a uniform 50 MPa stress
2. Contains three defect locations with 65 MPa stress
3. Has reduced stress (42.5 MPa) along the edges
4. Shows a gradually increasing stress from left to right due to gravity
5. Provides shape, size, and data type information for the array

The visualization should show a heatmap where:
- Brighter colors indicate higher stress
- The defect areas appear as bright spots
- The edges are darker due to heat treatment
- There's a gradient from left to right due to gravity

#### **Hints**

* For initializing the array with a uniform value, consider using `np.full()` or `np.ones()` multiplied by a scalar.
* When working with specific locations, direct indexing (`array[row, col] = value`) is effective.
* For the edges, remember that you can select entire rows or columns with slicing notation.
* For the gravity effect, `np.linspace()` can create a linearly increasing array that you can add to each row.
* Remember that arrays have attributes like `.shape`, `.size`, and `.dtype` to provide information about their structure.

#### **Challenge Completion**

You've successfully completed this challenge when:
1. You've implemented all five steps correctly
2. Your code produces a visualization that shows the combined effects of defects, heat treatment, and gravity
3. You can explain the array operations used to create this simulation

This challenge demonstrates how NumPy's array operations can be applied to model and visualize physical phenomena in engineering, showcasing the power of NumPy for scientific computing applications.

[⬆️ Back to the Top](#ue4-numpy)

---


## 📋 Chapter Summary

- **NumPy arrays** are the fundamental data structure for numerical computing in Python, offering optimized performance and memory efficiency for numerical operations.

- **Array creation** can be done through multiple methods:
  - From existing sequences with `np.array()`
  - With specialized functions like `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`
  - Using random number generators like `np.random.random()`

- **Data types** in NumPy arrays are homogeneous, with available types including:
  - Integers (`int8` through `int64`, plus unsigned versions)
  - Floating-point (`float16`, `float32`, `float64`)
  - Booleans, complex numbers, and more
  - Converting between types can be done with `astype()`

- **Array attributes** provide essential information:
  - `shape`: Dimensions of the array
  - `size`: Total number of elements
  - `ndim`: Number of dimensions
  - `dtype`: Data type of elements
  - `itemsize`/`nbytes`: Memory usage information

- **Indexing techniques** allow for accessing array elements:
  - Basic indexing: `arr[0]`, `arr[1, 2]`
  - Boolean indexing: `arr[arr > 5]`
  - Fancy indexing: `arr[[0, 2, 4]]`

- **Slicing techniques** help extract subarrays:
  - Basic slicing: `arr[start:stop:step]`
  - Multi-dimensional slicing: `arr[:, 1:3]`
  - Understanding views vs. copies is crucial

- **The Stress Analysis challenge** provided a practical application, demonstrating how NumPy operations can be used to simulate and analyze stress distribution in a metal pole.

## 🔮 Looking Ahead

In the next chapter, we'll explore **Operations with NumPy Arrays**. You'll learn how to perform various calculations, from simple arithmetic to complex mathematical functions, on entire arrays at once. This vectorized approach is one of NumPy's most powerful features, enabling you to write cleaner, more efficient code for numerical computations. We'll also explore broadcasting, which allows operations between arrays of different shapes.

## 📚 Key Terms

- **ndarray**: NumPy's N-dimensional array object, the core data structure for numerical computing
- **shape**: A tuple describing the size of each dimension in an array
- **dtype**: The data type of elements in a NumPy array
- **view**: A way to access array data that doesn't create a copy; changes to the view affect the original
- **copy**: A duplicate of an array's data that is independent of the original
- **slicing**: A technique to extract subarrays using the `start:stop:step` syntax
- **indexing**: Methods to access specific elements in an array
- **broadcasting**: NumPy's ability to perform operations on arrays of different shapes
- **vectorization**: Operating on entire arrays at once rather than element by element

## 🔍 Further Exploration

For those interested in diving deeper into NumPy arrays:

- Explore structured arrays for working with heterogeneous data
- Learn about masked arrays for handling missing values
- Investigate memory layout options (C-order vs. Fortran-order) for performance optimization
- Experiment with record arrays for database-like functionality
- Practice with more complex real-world applications that use NumPy arrays

[⬆️ Back to the Top](#ue4-numpy)

---