# **UE4: NumPy**

# **Chapter 03:** Operations with NumPy Arrays

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/512px-NumPy_logo_2020.svg.png" height="150">

## 🌟 Introduction

Now that you understand how to create and access NumPy arrays, it's time to explore what makes NumPy truly powerful: operations on arrays. Unlike Python's built-in lists, NumPy arrays are designed for efficient numerical operations, allowing you to perform calculations on entire arrays without explicit loops.

In this chapter, we'll dive into array operations that form the foundation of numerical computing in Python. You'll learn how to perform arithmetic operations across arrays, compute statistical measures from your data, and utilize broadcasting to work with arrays of different shapes. These capabilities are what make NumPy the cornerstone of scientific computing in Python.

> **Tip:** Think in terms of operations on entire arrays rather than individual elements. This "vectorized" thinking is not only more efficient computationally but also leads to cleaner, more readable code.

In this chapter, we'll follow a logical progression starting with basic arithmetic operations that give you the building blocks for array computations. We'll then explore statistical functions that allow you to analyze and summarize your data. Next, we'll cover broadcasting - a powerful feature that lets you work with arrays of different shapes. Finally, we'll apply these concepts to a real-world engineering problem in our continuing stress analysis challenge.

## 📚 Chapter Outline

> **[Chapter 3.1: Arithmetic Operations](#chapter-31-arithmetic-operations)**
- **Basic Arithmetic Operations:** Perform element-wise addition, subtraction, multiplication, and division with arrays
- **Mathematical Functions:** Apply functions like square root, exponential, and logarithm to arrays
- **Matrix Operations:** Understand the difference between element-wise multiplication and matrix multiplication

> **[Chapter 3.2: Statistical Functions](#chapter-32-statistical-functions)**
- **Basic Statistics:** Calculate mean, median, standard deviation, and other summary statistics
- **Aggregation Functions:** Work with functions like sum, min, and max across arrays
- **Axis-Based Calculations:** Perform operations along specific dimensions of multi-dimensional arrays

> **[Chapter 3.3: Broadcasting](#chapter-33-broadcasting)**
- **Broadcasting Concept:** Understand NumPy's rules for operating on arrays of different shapes
- **Broadcasting Mechanics:** Learn how arrays are virtually reshaped during operations
- **Practical Applications:** See real-world examples of broadcasting in action

> **[Chapter 3.4: Coding Challenge](#chapter-34-coding-challenge)**
- **Stress Analysis 2/3:** Apply array operations to analyze stress distribution in a metal pole

## 💡 What You Will Learn

By the end of this chapter, you will be able to:
- Perform element-wise arithmetic operations on NumPy arrays
- Apply universal mathematical functions to transform array data
- Calculate statistical measures like mean, median, and standard deviation
- Understand and leverage broadcasting to operate on arrays of different shapes
- Apply these operations to solve a real-world engineering problem

[⬆️ Back to the Top](#ue4-numpy)

---


## **Chapter 3.1:** Arithmetic Operations

### 🔍 Basic Arithmetic Operations

NumPy arrays support a wide range of arithmetic operations, allowing you to perform calculations on entire arrays at once. This **vectorized** approach is much faster than using loops and produces more concise, readable code.

When you perform arithmetic operations between NumPy arrays, the operations are applied **element-wise** - that is, the operation is performed on corresponding elements of the arrays. This is different from mathematical matrix operations, and it's important to understand the distinction.

### 🧩 Important Components

* **Element-wise Operations**: Operations applied to each element individually
* **Arithmetic Operators**: Standard operators like `+`, `-`, `*`, `/` work with arrays
* **Mathematical Functions**: NumPy provides functions like `np.sqrt()`, `np.exp()`, etc.
* **Matrix Operations**: Special functions for true matrix operations like `np.dot()`

    | Operation | Operator | NumPy Function | Example |
    |-----------|----------|---------------|---------|
    | Addition | `+` | `np.add()` | `a + b` or `np.add(a, b)` |
    | Subtraction | `-` | `np.subtract()` | `a - b` or `np.subtract(a, b)` |
    | Multiplication | `*` | `np.multiply()` | `a * b` or `np.multiply(a, b)` |
    | Division | `/` | `np.divide()` | `a / b` or `np.divide(a, b)` |
    | Power | `**` | `np.power()` | `a ** 2` or `np.power(a, 2)` |
    | Modulus | `%` | `np.mod()` | `a % 2` or `np.mod(a, 2)` |

### 📘 Main Content

#### Element-wise Arithmetic

Let's start by creating two simple arrays and exploring basic arithmetic operations:



In [ ]:
import numpy as np

# Creating two arrays for our examples
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print("Array 1:", array1)
print("Array 2:", array2)


Now let's perform basic arithmetic operations on these arrays:



In [ ]:
# Addition
sum_result = array1 + array2
print("Addition:", sum_result)  # Output: [6 8 10 12]

In [ ]:
# Subtraction
difference = array2 - array1
print("Subtraction:", difference)  # Output: [4 4 4 4]

In [ ]:
# Multiplication
product = array1 * array2
print("Multiplication:", product)  # Output: [5 12 21 32]

In [ ]:
# Division
quotient = array2 / array1
print("Division:", quotient)  # Output: [5. 3. 2.33... 2.]


These operations are applied element-wise, meaning they operate on corresponding elements of the arrays. For example, in the addition operation, the first element of `array1` is added to the first element of `array2`, the second element to the second element, and so on.

#### Operations with Scalars

NumPy allows you to perform operations between arrays and scalar values (single numbers). In this case, the scalar value is applied to every element in the array:



In [ ]:
# Create an array
array = np.array([1, 2, 3, 4, 5])

# Scalar operations
print("Original array:", array)
print("Add scalar:", array + 10)  # Output: [11 12 13 14 15]
print("Multiply by scalar:", array * 2)  # Output: [2 4 6 8 10]
print("Power operation:", array ** 2)  # Output: [1 4 9 16 25]


This capability is particularly useful for data normalization, scaling, and offset adjustments in scientific and engineering applications.

#### Mathematical Functions

NumPy provides a comprehensive set of mathematical functions that operate element-wise on arrays. These include trigonometric functions, exponential and logarithmic functions, and many others:



In [ ]:
# Create an array for demonstration
array = np.array([0, 30, 45, 60, 90])
angles = np.radians(array)  # Convert degrees to radians

In [ ]:
# Trigonometric functions
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

In [ ]:
# Another example with different functions
values = np.array([1, 2, 3, 4, 5])
print("Square root:", np.sqrt(values))
print("Exponential (e^x):", np.exp(values))
print("Natural logarithm:", np.log(values))


These functions are optimized for performance and work consistently across different array shapes and sizes.

#### Matrix Operations

While element-wise operations are common, NumPy also provides functions for true matrix operations. The most important distinction is between element-wise multiplication (`*`) and matrix multiplication (`@` or `np.dot()`):



In [ ]:
# Create two 2D arrays (matrices)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

In [ ]:
# Element-wise multiplication
element_wise_product = A * B
print("Element-wise multiplication (A * B):\n", element_wise_product)

In [ ]:
# Matrix multiplication
matrix_product = A @ B  # Equivalent to np.dot(A, B)
print("Matrix multiplication (A @ B):\n", matrix_product)


The difference is crucial:
- Element-wise multiplication (`*`) multiplies corresponding elements
- Matrix multiplication (`@` or `np.dot()`) follows the rules of linear algebra matrix multiplication

Understanding when to use each type of operation is essential for correct implementation of mathematical algorithms and models.

### ⚠️ Common Mistakes with Array Operations

* **Shape mismatch**: Attempting operations on arrays with incompatible shapes without using broadcasting
* **Confusing element-wise and matrix multiplication**: Using `*` when you meant `@` or vice versa
* **Dimension errors**: Applying operations on arrays with incorrect dimensions
* **In-place modification**: Forgetting that operations like `a + b` create a new array rather than modifying existing ones

### 🔄 Quick Check: Arithmetic Operations

What will be the output of the following code?

```python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b + 2
```

<details>
   <summary>View Answer</summary>

   ```
   [6 12 20]
   ```

   Explanation:
   1. First, `a * b` performs element-wise multiplication: `[1*4, 2*5, 3*6]` = `[4, 10, 18]`
   2. Then, `+ 2` adds 2 to each element: `[4+2, 10+2, 18+2]` = `[6, 12, 20]`
</details>

In another example, what's the difference between these two operations?

```python
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result1 = A * B
result2 = A @ B
```

<details>
   <summary>View Answer</summary>

   `result1` is element-wise multiplication:
   ```
   [[ 5 12]
    [21 32]]
   ```

   `result2` is matrix multiplication:
   ```
   [[19 22]
    [43 50]]
   ```

   Matrix multiplication follows the rule where (A @ B)[i,j] = sum(A[i,:] * B[:,j])
</details>

### 📚 Further Reading: Array Operations

* [NumPy Mathematical Functions](https://numpy.org/doc/stable/reference/routines.math.html) - Complete list of math functions
* [Linear Algebra with NumPy](https://numpy.org/doc/stable/reference/routines.linalg.html) - Documentation for matrix operations
* [A Visual Guide to NumPy Operations](https://jalammar.github.io/visual-numpy/) - Visual explanations of NumPy operations

[⬆️ Back to the Top](#ue4-numpy)

---



## 👨‍💻 **Practice Tasks 3.1:** Array Arithmetic Operations

Now it's time to apply what you've learned about arithmetic operations with NumPy arrays. Complete the following tasks:

**Basic Arithmetic:**

1. Create two 1D arrays `array_a` with values [10, 20, 30, 40] and `array_b` with values [1, 2, 3, 4].

2. Perform and print the results of:
   - Adding the two arrays
   - Subtracting `array_b` from `array_a`
   - Multiplying the two arrays element-wise
   - Dividing `array_a` by `array_b`

**Operations with Scalars:**

3. Using `array_a` from above:
   - Add 5 to every element
   - Multiply every element by 2
   - Calculate the square root of every element using `np.sqrt()`
   - Raise every element to the power of 2

**Matrix Operations:**

4. Create two 2×2 matrices:
   ```python
   matrix_a = np.array([[1, 2], [3, 4]])
   matrix_b = np.array([[5, 6], [7, 8]])
   ```

5. Calculate and print:
   - The element-wise product of the matrices
   - The matrix product of the matrices using `@` or `np.dot()`
   - The sum of all elements in each matrix using `np.sum()`

**Combining Operations:**

6. Create a 1D array of values [1, 2, 3, 4, 5] and in a single expression:
   - Multiply each value by 2
   - Add 10
   - Calculate the square of the result

---

*Basic Arithmetic:*

In [ ]:
# 1. Create two 1D arrays


In [ ]:
# 2. Perform arithmetic operations



*Operations with Scalars:*



In [ ]:
# 3. Scalar operations with array_a



*Matrix Operations:*



In [ ]:
# 4. Create two 2×2 matrices


In [ ]:
# 5. Matrix operations



*Combining Operations:*



In [ ]:
# 6. Combined operations in a single expression



[⬆️ Back to the Top](#ue4-numpy)

---



## **Chapter 3.2:** Statistical Functions

### 🔍 Basic Statistics

One of NumPy's most powerful features is its ability to efficiently compute statistical measures across large datasets. These functions can analyze entire arrays at once, saving you from writing loops and significantly improving performance. Whether you're analyzing scientific measurements, financial data, or machine learning features, NumPy's statistical functions provide the essential tools.

Statistical functions in NumPy can operate on the entire array or along specified axes in multi-dimensional arrays, giving you flexibility in how you analyze your data.

### 🧩 Important Components

* **Central Tendency**: Functions like `mean()`, `median()`, and `percentile()` that describe the center of your data
* **Dispersion**: Functions like `std()` (standard deviation), `var()` (variance), and `min()`/`max()` that describe the spread of your data
* **Aggregation**: Functions like `sum()`, `prod()` (product), `cumsum()` (cumulative sum) that combine values
* **Axis Parameter**: Most statistical functions accept an `axis` parameter to specify which dimension to operate along

    | Function | Description | Example |
    |----------|-------------|---------|
    | `np.mean(array)` | Calculates the arithmetic mean | `np.mean([1, 2, 3])` → `2.0` |
    | `np.median(array)` | Calculates the median value | `np.median([1, 2, 100])` → `2.0` |
    | `np.std(array)` | Calculates the standard deviation | `np.std([1, 2, 3])` → `0.816...` |
    | `np.var(array)` | Calculates the variance | `np.var([1, 2, 3])` → `0.667...` |
    | `np.min(array)` | Finds the minimum value | `np.min([5, 2, 8])` → `2` |
    | `np.max(array)` | Finds the maximum value | `np.max([5, 2, 8])` → `8` |
    | `np.percentile(array, q)` | Calculates the q-th percentile | `np.percentile([1, 2, 3, 4], 75)` → `3.25` |

### 📘 Main Content

#### Basic Statistical Measures

Let's explore basic statistical functions using a simple array:



In [ ]:
import numpy as np

# Create an array of data
data = np.array([15, 23, 42, 19, 27, 35, 10])
print("Data array:", data)

In [ ]:
# Calculate basic statistics
print("Mean:", np.mean(data))  # Average of all values
print("Median:", np.median(data))  # Middle value
print("Standard deviation:", np.std(data))  # Measure of spread
print("Variance:", np.var(data))  # Square of standard deviation
print("Minimum:", np.min(data))  # Smallest value
print("Maximum:", np.max(data))  # Largest value


These functions give you a comprehensive overview of your data's characteristics, which is essential for statistical analysis and data exploration.

#### Aggregation Functions

Aggregation functions combine multiple values into a single result. This is useful for calculating totals, products, or running tallies:



In [ ]:
import numpy as np

# Create an example array
data = np.array([1, 2, 3, 4, 5])
data

In [ ]:
# Sum of all elements
print("Sum:", np.sum(data))  # Output: 15

In [ ]:
# Product of all elements
print("Product:", np.prod(data))  # Output: 120

In [ ]:
# Cumulative sum (running total)
print("Cumulative sum:", np.cumsum(data))  # Output: [1 3 6 10 15]

In [ ]:
# Cumulative product
print("Cumulative product:", np.cumprod(data))  # Output: [1 2 6 24 120]

Cumulative functions are particularly useful for calculating running totals or products, which have applications in finance, physics, and many other fields.

#### Axis-Based Calculations

When working with multi-dimensional arrays, you often need to calculate statistics along specific dimensions. The `axis` parameter lets you specify which dimension to operate along:

- `axis=0`: Operate along columns (down)
- `axis=1`: Operate along rows (across)
- `axis=None`: Operate on the flattened array (default)

Let's see how this works with a 2D array:

In [ ]:
import numpy as np

# Create a 2D array (3x4 matrix)
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original matrix:")
print(matrix)

# Calculate mean along different axes
print("\nMean of entire matrix:", np.mean(matrix))  # All elements
print("Mean of each column (axis=0):", np.mean(matrix, axis=0))  # Down each column
print("Mean of each row (axis=1):", np.mean(matrix, axis=1))  # Across each row


You can see that:
- The mean of the entire matrix is 6.5
- The means of the columns are [5, 6, 7, 8]
- The means of the rows are [2.5, 6.5, 10.5]

This axis-based functionality extends to all statistical functions in NumPy.

#### More Complex Statistical Analysis

NumPy also provides more advanced statistical functions:



In [ ]:
import numpy as np

# Create a sample dataset
data = np.array([2, 4, 4, 4, 5, 5, 7, 8, 8, 9, 12, 14, 14])
data

In [ ]:
# Calculate various statistics
print("25th percentile:", np.percentile(data, 25))  # First quartile
print("50th percentile (median):", np.percentile(data, 50))  # Median
print("75th percentile:", np.percentile(data, 75))  # Third quartile

print("Interquartile range (IQR):", np.percentile(data, 75) - np.percentile(data, 25))

In [ ]:
# Correlation and covariance
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 7, 9, 11, 13])  # Perfectly correlated with x

print("Correlation coefficient:", np.corrcoef(x, y)[0, 1])  # Should be close to 1
print("Covariance matrix:\n", np.cov(x, y))


These advanced functions help you understand relationships between variables and distributions of your data, which is crucial for statistical modeling and hypothesis testing.

### ⚠️ Common Mistakes with Statistical Functions

* **Forgetting array dimensionality**: Failing to specify an axis when working with multi-dimensional arrays may lead to unexpected results
* **Misinterpreting axes**: Confusing axis=0 (columns) and axis=1 (rows) in statistical calculations
* **Not handling missing values**: NumPy statistical functions don't ignore NaN values by default, unlike some other libraries
* **Precision issues**: Variance and standard deviation calculations might have slight precision differences from mathematical definitions

### 🔄 Quick Check: Statistical Functions

What will be the output of the following code?

```python
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.sum(arr, axis=1)

```

<details>
   <summary>View Answer</summary>

   ```
   [6 15]
   ```

   Explanation:
   - `axis=1` means summing across rows
   - First row: 1 + 2 + 3 = 6
   - Second row: 4 + 5 + 6 = 15
</details>

Extra: What is the standard deviation of the array `[1, 1, 1, 1]`?

<details>
   <summary>View Answer</summary>

   ```
   0.0
   ```

   Explanation:
   - The standard deviation is a measure of dispersion or spread
   - Since all values are identical (1), there is no spread, so the standard deviation is 0
</details>

### 📚 Further Reading: Statistical Functions

* [NumPy Statistical Functions](https://numpy.org/doc/stable/reference/routines.statistics.html) - Complete documentation
* [Introduction to Statistics with NumPy](https://realpython.com/numpy-statistics/) - Practical guide on Real Python
* [Statistical Data Visualization](https://seaborn.pydata.org/tutorial/distributions.html) - Using Seaborn with NumPy for visualizing statistical data

[⬆️ Back to the Top](#ue4-numpy)

---


## 👨‍💻 Practice Tasks 3.2: Statistical Functions

Now let's practice applying NumPy's statistical functions to analyze data. Complete the following tasks:

#### **Basic Statistics:**

1. Create a 1D array with the values [14, 23, 32, 41, 50, 67, 74, 81, 98] and calculate:
   - The mean using `np.mean()`
   - The median using `np.median()`
   - The minimum and maximum values using `np.min()` and `np.max()`
   - The standard deviation using `np.std()`
   - The variance using `np.var()`
   - The 25th, 50th, and 75th percentiles using `np.percentile()`

#### **Working with Multi-dimensional Arrays:**

2. Create the following 2D array:
   ```python
   data = np.array([
       [10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 100, 110, 120]
   ])
   ```

3. Calculate the following statistics and explain the results:
   - The mean of the entire array using `np.mean()`
   - The mean of each column using `np.mean(data, axis=0)`
   - The mean of each row using `np.mean(data, axis=1)`
   - The standard deviation of the entire array using `np.std()`
   - The minimum value in each row using `np.min(data, axis=1)`

#### **Statistical Analysis of Random Data:**

4. Generate an array of 1000 random numbers using `np.random.normal(50, 10, 1000)` (normal distribution with mean=50, std=10).

5. For this random data, calculate and print:
   - The mean and median (should be close to 50)
   - The standard deviation (should be close to 10)
   - The 5th and 95th percentiles
   - The histogram bins using `np.histogram(data, bins=10)`

#### **Data Comparison:**

6. Create two arrays:
   ```python
   data1 = np.array([15, 20, 25, 30, 35, 40, 45])
   data2 = np.array([14, 21, 23, 35, 37, 43, 44])
   ```

7. Compare these datasets by calculating:
   - The difference in their means
   - The difference in their standard deviations
   - The correlation coefficient between them using `np.corrcoef()`

---

*Basic Statistics:*

In [ ]:
# 1. Basic statistics on a 1D array



*Working with Multi-dimensional Arrays:*



In [ ]:
# 2-3. Statistics on a 2D array



*Statistical Analysis of Random Data:*



In [ ]:
# 4-5. Analysis of random data



*Data Comparison:*



In [ ]:
# 6-7. Comparing two datasets



[⬆️ Back to the Top](#ue4-numpy)

---



## **Chapter 3.3:** Broadcasting

### 🔍 Broadcasting Concept

Broadcasting is one of NumPy's most powerful features, allowing you to perform operations between arrays of different shapes without explicitly reshaping them. This capability enables concise, efficient code by automating the process of making arrays compatible for element-wise operations.

At its core, broadcasting is a set of rules that NumPy uses to decide how arrays of different shapes can interact. Without broadcasting, you would need to manually resize arrays using loops or repetition, making your code more verbose and potentially less efficient.

### 🧩 Important Components

* **Broadcasting Rules**: The specific rules NumPy follows to make arrays compatible
* **Dimension Compatibility**: Conditions for shapes to be compatible for broadcasting
* **Shape Alignment**: How NumPy aligns arrays of different dimensions
* **Efficiency Benefits**: Memory and computation savings compared to explicit reshaping

    | Concept | Description | Example |
    |---------|-------------|---------|
    | Shape compatibility | Arrays are compatible when dimensions match or one is 1 | (3,4) and (3,1) are compatible |
    | Array alignment | Smaller arrays are "broadcast" across larger ones | A 1D array (3,) becomes (1,3) for operations with a (4,3) array |
    | Dimension matching | Arrays are compared from trailing dimensions | (3,4,5) and (4,5) are compatible |
    | Dimension extension | Dimensions of size 1 are stretched to match larger dimensions | (3,1) becomes (3,4) when operating with a (3,4) array |

### 📘 Main Content

#### Broadcasting Mechanics

To understand broadcasting, let's start with a simple example:

In [ ]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3])

# Add a scalar to the array
result = a + 10

print("Original array:", a)
print("Result:", result)  # Output: [11 12 13]



In this example, the scalar value `10` is "broadcast" to the same shape as the array `a`, as if NumPy had created a new array `[10, 10, 10]` to perform the addition. However, NumPy does this without actually creating the additional array, saving memory and computation time.

Let's look at a slightly more complex example:



In [ ]:
import numpy as np

# Create a column vector (shape: (3,1))
col_vector = np.array([[1], [2], [3]])

# Create a row vector (shape: (1,4))
row_vector = np.array([[10, 20, 30, 40]])

In [ ]:
# Perform addition (broadcasting)
result = col_vector + row_vector

print("Column vector shape:", col_vector.shape)
print("Row vector shape:", row_vector.shape)
print("Result shape:", result.shape)
print("Result:\n", result)

This demonstrates how broadcasting works:
1. The column vector `(3×1)` is virtually expanded to a `(3×4)` array
2. The row vector `(1×4)` is virtually expanded to a `(3×4)` array
3. The operation is performed element-wise as if both were `(3×4)` arrays

#### Understanding Broadcasting Rules

NumPy follows a specific set of rules to determine when broadcasting is possible:

1. If arrays don't have the same rank (number of dimensions), prepend dimensions of size 1 to the shape of the lower-rank array until both arrays have the same rank.

2. Arrays are compatible for broadcasting if for each dimension, their sizes match or one of them has size 1.

3. In the operation, dimensions with size 1 are stretched to match the size of the other array in that dimension.

Let's illustrate this with a few examples:

In [51]:
import numpy as np

# Case 1: Broadcasting a scalar to an array
a = np.array([1, 2, 3, 4])  # Shape: (4,)
b = 10                       # Shape: ()
# b is broadcast to: (4,)
print("a + b:", a + b) 

a + b: [11 12 13 14]


In [50]:
# Case 2: Broadcasting arrays of different shapes
c = np.array([[1, 2, 3],     # Shape: (2,3)
              [4, 5, 6]])
d = np.array([10, 20, 30])   # Shape: (3,)
# d is broadcast to: (2,3)
print("c + d:\n", c + d)

c + d:
 [[11 22 33]
 [14 25 36]]


In [52]:
# Case 3: Broadcasting with incompatible shapes (will raise an error)
e = np.array([[1, 2],        # Shape: (2,2)
              [3, 4]])
f = np.array([5, 6, 7])      # Shape: (3,)

# These shapes are incompatible for broadcasting
try:
    print("e + f:", e + f)
except ValueError as err:
    print("Error:", err)

Error: operands could not be broadcast together with shapes (2,2) (3,) 



In Case 3, the shapes (2,2) and (3,) are incompatible because the trailing dimensions (2 and 3) do not match and neither is 1.

#### Practical Applications

Broadcasting has numerous practical applications in data analysis, scientific computing, and machine learning. Here are some common use cases:

**Centering Data:**



In [ ]:
import numpy as np

# Create a 2D array of measurements (e.g., 4 samples, 3 features)
measurements = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])

# Calculate the mean of each feature (column)
feature_means = np.mean(measurements, axis=0)  # Shape: (3,)

# Center the data by subtracting the mean
# Broadcasting: (4,3) - (3,) -> (4,3) - (1,3) -> (4,3)
centered_data = measurements - feature_means

print("Original measurements:\n", measurements)
print("Feature means:", feature_means)
print("Centered data:\n", centered_data)


This is a common preprocessing step in machine learning, where centering data (subtracting the mean) helps with algorithm convergence.

**Normalizing Multiple Images:**



In [53]:
import numpy as np

# Simulate 3 grayscale images of size 4x4
images = np.random.randint(0, 256, size=(3, 4, 4))

# Calculate min and max values for each image
min_vals = np.min(images, axis=(1, 2))  # Shape: (3,)
max_vals = np.max(images, axis=(1, 2))  # Shape: (3,)

# Reshape to allow broadcasting
min_vals = min_vals.reshape(3, 1, 1)  # Shape: (3,1,1)
max_vals = max_vals.reshape(3, 1, 1)  # Shape: (3,1,1)

# Normalize each image to [0,1] range
# Broadcasting happens automatically
normalized_images = (images - min_vals) / (max_vals - min_vals)

print("Original image 0 (sample):\n", images[0])
print("Normalized image 0 (sample):\n", normalized_images[0])

Original image 0 (sample):
 [[156  94 172 184]
 [ 99 220  91 236]
 [ 81 148 227 198]
 [ 53 207 170 100]]
Normalized image 0 (sample):
 [[0.56284153 0.22404372 0.65027322 0.71584699]
 [0.25136612 0.91256831 0.20765027 1.        ]
 [0.15300546 0.51912568 0.95081967 0.79234973]
 [0.         0.84153005 0.63934426 0.2568306 ]]



Here, broadcasting allows us to normalize each image independently using its own min and max values.

**Distance Calculations:**



In [54]:
import numpy as np

# Create 3 points in 2D space
points = np.array([[0, 0],
                   [1, 2],
                   [3, 4]])

# Calculate distance from each point to the origin
# Using broadcasting and the Euclidean distance formula: sqrt(x² + y²)
distances = np.sqrt(np.sum(points**2, axis=1))

print("Points:", points)
print("Distances from origin:", distances)

# Calculate pairwise distances between points
# Broadcasting the operation: (3,1,2) - (1,3,2) -> (3,3,2)
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
pairwise_distances = np.sqrt(np.sum(diff**2, axis=2))

print("Pairwise distances:\n", pairwise_distances)

Points: [[0 0]
 [1 2]
 [3 4]]
Distances from origin: [0.         2.23606798 5.        ]
Pairwise distances:
 [[0.         2.23606798 5.        ]
 [2.23606798 0.         2.82842712]
 [5.         2.82842712 0.        ]]



This example shows how broadcasting can be used for complex geometric calculations without loops.

### ⚠️ Common Mistakes with Broadcasting

* **Shape incompatibility**: Attempting to broadcast arrays with incompatible shapes
* **Unexpected broadcasting**: Not accounting for automatic broadcasting, leading to unexpected operations
* **Dimension confusion**: Misunderstanding which dimensions will be broadcast
* **Performance issues**: Broadcasting very large dimensions can sometimes be memory-intensive

### 🔄 Quick Check: Broadcasting

Which of the following pairs of array shapes can be broadcast together?

1. (3, 4) and (4,)
2. (3, 4) and (3,)
3. (3, 4) and (2, 4)
4. (3, 4, 5) and (4, 5)
5. (3, 4, 5) and (3, 1, 5)

<details>
   <summary>View Answer</summary>

   Compatible pairs are: 1, 4, and 5.

   Explanations:
   1. (3, 4) and (4,) - Compatible: The (4,) array is broadcast to shape (1, 4) and then to (3, 4).
   2. (3, 4) and (3,) - Incompatible: The trailing dimensions (4 and 3) don't match.
   3. (3, 4) and (2, 4) - Incompatible: The first dimensions (3 and 2) don't match and neither is 1.
   4. (3, 4, 5) and (4, 5) - Compatible: The (4, 5) array is broadcast to (1, 4, 5) and then to (3, 4, 5).
   5. (3, 4, 5) and (3, 1, 5) - Compatible: The dimension with size 1 is stretched to match size 4.
</details>

### 📚 Further Reading: Broadcasting

* [Broadcasting in NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html) - Official NumPy documentation
* [A Visual Guide to NumPy Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) - From the Python Data Science Handbook
* [Understanding NumPy Broadcasted Operations](https://scipy-lectures.org/intro/numpy/operations.html) - SciPy Lectures

[⬆️ Back to the Top](#ue4-numpy)

---



## 👨‍💻 **Practice Tasks 3.3:** Broadcasting

Now it's time to apply what you've learned about NumPy's broadcasting capabilities. Complete the following tasks:

**Simple Broadcasting:**

1. Create a 1D array `prices` with values [10, 20, 30, 40, 50].

2. Use broadcasting to:
   - Add 5 to each price
   - Apply a 10% discount to all prices
   - Calculate prices after applying a sales tax of 8%

**Matrix Operations with Broadcasting:**

3. Create a 3×4 matrix of random integers between 1 and 100:

    ```python
    data_matrix = np.random.randint(1, 100, size=(3, 4))
    ```

4. Use broadcasting to:
   - Subtract the mean of each column from the corresponding column
   - Divide each row by the sum of that row to normalize rows
   - Add a row vector [1, 2, 3, 4] to each row

**Advanced Broadcasting:**

5. Create a dataset representing the monthly sales for 3 products across 4 quarters:

    ```python
    sales = np.array([
        [100, 120, 140, 90],    # Product 1
        [80, 95, 110, 70],      # Product 2
        [150, 160, 170, 180]    # Product 3
    ])
    ```

6. Use broadcasting to:
   - Calculate the percentage each quarter contributes to the annual sales for each product
   - Apply different discount rates [0.1, 0.15, 0.2] to each product (all quarters)
   - Calculate the difference from the average sales for each product and quarter

**Real-world Application - Temperature Conversion:**

7. Create an array representing daily temperatures in Celsius for a week:

   ```python
   celsius_temps = np.array([20, 22, 19, 25, 27, 24, 21])
   ```

8. Use broadcasting to:
   - Convert all temperatures to Fahrenheit using the formula F = C × 9/5 + 32
   - Calculate the difference between each day's temperature and the weekly average
   - Determine how many degrees above or below the monthly normal temperatures [18, 19, 19, 20, 21, 21, 20] each day was

*Simple Broadcasting:*



In [ ]:
# 1-2. Working with prices



*Matrix Operations with Broadcasting:*



In [ ]:
# 3-4. Broadcasting with matrices



*Advanced Broadcasting:*



In [ ]:
# 5-6. Working with sales data



*Real-world Application - Temperature Conversion:*



In [ ]:
# 7-8. Temperature conversions



[⬆️ Back to the Top](#ue4-numpy)

---



## **Chapter 3.4:** Coding Challenge

### 🏆 Stress Analysis 2/3

In this coding challenge, we'll continue the case study from the previous chapter. Our goal is to further analyze the stress distribution in a metal pole, applying more advanced NumPy array operations and statistical techniques. This will demonstrate how NumPy's capabilities can be applied to real-world engineering problems.

#### **Task Background:**

In materials engineering, understanding stress distribution is crucial for preventing structural failures. We'll continue our simulation of stress in a metal pole, now incorporating array operations, threshold analysis, and statistical measures.

#### **Step-by-step Goals:**

**Step 0: Restore the stress distribution**

We'll begin by reinitializing the stress distribution from the first part of our case study:



In [ ]:
import numpy as np
from matplotlib import pyplot as plt

# Function to visualize the pole (same as before)
def plot_pole(arr):
    plt.figure(figsize=(10, 3))
    plt.imshow(arr, cmap='viridis')
    plt.colorbar(label='Stress (MPa)')
    plt.title('Metal Pole Stress Distribution')
    plt.xlabel('Length')
    plt.ylabel('Width')
    plt.show()

# Step 0: Reinitialize the stress distribution
# Create a 5×25 array to represent a metal pole with uniform initial stress
stress_distribution = np.full((5, 25), 50, dtype=np.float64)

# Apply material errors (specific defects)
material_errors = [(3, 13), (1, 21), (4, 2)]
for error in material_errors:
    stress_distribution[error] = 65

# Apply heat treatment to edges (15% stress reduction)
stress_distribution[0, :] *= 0.85  # Top edge
stress_distribution[-1, :] *= 0.85  # Bottom edge
stress_distribution[:, 0] *= 0.85  # Front edge
stress_distribution[:, -1] *= 0.85  # Back edge

# Display the initial state
print("Initial stress distribution:")
print(stress_distribution)
plot_pole(stress_distribution)



**Step 1: Apply a Linear Force for Gravity (using broadcasting)**

In this step, we'll use broadcasting to apply a linearly increasing gravitational force from the left side (fixed to a wall) to the right side (free end):



In [ ]:
# Step 1: Apply gravity effect using broadcasting
# Create a linearly increasing force from 0 to 12 MPa
gravity_effect = np.linspace(0, 12, 25)

# Use broadcasting to apply this effect to each row of the pole
stress_distribution += gravity_effect  # Broadcasting in action!

print("Stress distribution after applying gravity effect:")
print(stress_distribution)
plot_pole(stress_distribution)



Here we're using NumPy's broadcasting capability to add the 1D `gravity_effect` array to the 2D `stress_distribution` array. This is much more elegant and efficient than using loops to apply the effect.

**Step 2: Apply an Absolute High-Stress Threshold**

Safety specifications often require identifying areas where stress exceeds certain thresholds. We'll use boolean indexing to identify these regions:



In [ ]:
# Step 2: Identify high-stress areas using boolean indexing
high_stress_threshold = 60
high_stress_areas = stress_distribution > high_stress_threshold

print("Areas with high stress (>60 MPa):")
print(high_stress_areas)
plot_pole(high_stress_areas)



This step demonstrates how to use comparison operations and boolean indexing to identify critical regions in the structure.

**Step 3: Identify Areas with Low Stress**

Similarly, we'll identify areas that have less stress than the average:



In [ ]:
# Step 3: Identify areas with low relative stress
# Calculate the mean stress across the entire pole
mean_stress = np.mean(stress_distribution)
low_stress_threshold = 0.90 * mean_stress  # 90% of the mean

# Use boolean indexing to find areas below this threshold
low_stress_areas = stress_distribution < low_stress_threshold

print(f"Mean stress: {mean_stress:.2f} MPa")
print(f"Low stress threshold (90% of mean): {low_stress_threshold:.2f} MPa")
print("Areas with low relative stress:")
print(low_stress_areas)
plot_pole(low_stress_areas)


Here we're combining statistical functions with boolean operations to identify areas of potential concern.

**Step 4: Calculate Key Statistical Metrics**

Finally, we'll compute important statistical measures to better understand the stress distribution:



In [ ]:
# Step 4: Calculate and report key statistical metrics
median_stress = np.median(stress_distribution)
std_dev_stress = np.std(stress_distribution)
min_stress = np.min(stress_distribution)
max_stress = np.max(stress_distribution)

print("\nStatistical Analysis of Stress Distribution:")
print(f"Median Stress: {median_stress:.2f} MPa")
print(f"Standard Deviation: {std_dev_stress:.2f} MPa")
print(f"Minimum Stress: {min_stress:.2f} MPa")
print(f"Maximum Stress: {max_stress:.2f} MPa")

# Additional analysis: Calculate stress quartiles
quartiles = np.percentile(stress_distribution, [25, 50, 75])
print(f"First Quartile (25%): {quartiles[0]:.2f} MPa")
print(f"Second Quartile (50%, median): {quartiles[1]:.2f} MPa")
print(f"Third Quartile (75%): {quartiles[2]:.2f} MPa")
print(f"Interquartile Range: {(quartiles[2] - quartiles[0]):.2f} MPa")


These statistical measures provide valuable insights into the overall distribution of stress in the structure.

#### **Complete Solution**

Here's a complete solution that implements all steps and visualizes the result:



In [ ]:
import numpy as np
from matplotlib import pyplot as plt

# Function to visualize the pole
def plot_pole(arr):
    plt.figure(figsize=(10, 3))
    plt.imshow(arr, cmap='viridis')
    plt.colorbar(label='Stress (MPa)')
    plt.title('Metal Pole Stress Distribution')
    plt.xlabel('Length')
    plt.ylabel('Width')
    plt.show()

# Step 0: Reinitialize the stress distribution
# Create a 5×25 array to represent a metal pole with uniform initial stress
stress_distribution = np.full((5, 25), 50, dtype=np.float64)

# Apply material errors (specific defects)
material_errors = [(3, 13), (1, 21), (4, 2)]
for error in material_errors:
    stress_distribution[error] = 65

# Apply heat treatment to edges (15% stress reduction)
stress_distribution[0, :] *= 0.85  # Top edge
stress_distribution[-1, :] *= 0.85  # Bottom edge
stress_distribution[:, 0] *= 0.85  # Front edge
stress_distribution[:, -1] *= 0.85  # Back edge

print("Initial stress distribution created")
plot_pole(stress_distribution)

# Step 1: Apply gravity effect using broadcasting
# Create a linearly increasing force from 0 to 12 MPa
gravity_effect = np.linspace(0, 12, 25)

# Use broadcasting to apply this effect to each row of the pole
stress_distribution += gravity_effect  # Broadcasting in action!

print("Gravity effect applied")
plot_pole(stress_distribution)

# Step 2: Identify high-stress areas using boolean indexing
high_stress_threshold = 60
high_stress_areas = stress_distribution > high_stress_threshold

print("High-stress areas identified")
plot_pole(high_stress_areas)

# Step 3: Identify areas with low relative stress
# Calculate the mean stress across the entire pole
mean_stress = np.mean(stress_distribution)
low_stress_threshold = 0.90 * mean_stress  # 90% of the mean

# Use boolean indexing to find areas below this threshold
low_stress_areas = stress_distribution < low_stress_threshold

print(f"Mean stress: {mean_stress:.2f} MPa")
print(f"Low stress threshold (90% of mean): {low_stress_threshold:.2f} MPa")
print("Low-stress areas identified")
plot_pole(low_stress_areas)

# Step 4: Calculate and report key statistical metrics
median_stress = np.median(stress_distribution)
std_dev_stress = np.std(stress_distribution)
min_stress = np.min(stress_distribution)
max_stress = np.max(stress_distribution)

print("\nStatistical Analysis of Stress Distribution:")
print(f"Median Stress: {median_stress:.2f} MPa")
print(f"Standard Deviation: {std_dev_stress:.2f} MPa")
print(f"Minimum Stress: {min_stress:.2f} MPa")
print(f"Maximum Stress: {max_stress:.2f} MPa")

# Additional analysis: Calculate stress quartiles
quartiles = np.percentile(stress_distribution, [25, 50, 75])
print(f"First Quartile (25%): {quartiles[0]:.2f} MPa")
print(f"Second Quartile (50%, median): {quartiles[1]:.2f} MPa")
print(f"Third Quartile (75%): {quartiles[2]:.2f} MPa")
print(f"Interquartile Range: {(quartiles[2] - quartiles[0]):.2f} MPa")


#### **Engineering Insights:**

This challenge demonstrates how NumPy enables engineers to:

1. **Efficiently model physical phenomena** using broadcasting and vectorized operations
2. **Identify critical regions** where stress exceeds safety thresholds
3. **Quantify the distribution of stress** using statistical methods
4. **Visualize complex data** to gain insights into structural behavior

In real-world engineering applications, these capabilities are essential for designing safe, reliable structures and predicting potential failure modes.

#### **Key NumPy Features Demonstrated:**

- Broadcasting for efficient application of varying forces
- Boolean indexing for threshold-based analysis
- Statistical functions for quantitative assessment
- Vectorized operations for clean, readable code

In the next part of this challenge (3/3), we'll explore more advanced array manipulations to further enhance our stress analysis model.

#### **Expected Output:**

The completed challenge should produce visualizations showing:
1. The stress distribution with gravity effect applied
2. Areas exceeding the high-stress threshold
3. Areas below the low-stress threshold

It should also output statistical measures that characterize the stress distribution across the entire pole.

#### **Analysis and Interpretation:**

This simulation demonstrates several key engineering principles:

1. **Stress gradients due to gravity**: The gravitational effect creates a stress gradient that increases from the fixed end to the free end of the pole, a common pattern in horizontal cantilever structures.

2. **Critical stress regions**: The boolean indexing identifies areas where stress exceeds safety thresholds, which would be priority areas for reinforcement in real-world applications.

3. **Statistical characterization**: The quartile analysis provides a comprehensive overview of how stress is distributed throughout the structure, enabling better decision-making about material selection and geometric design.

4. **Edge effects**: The heat treatment applied to edges shows how manufacturing processes can modify stress distribution, potentially mitigating stress concentration at boundaries.

In the next part of this challenge, we'll explore how these stress patterns evolve over time when the structure is subjected to cyclic loading, introducing concepts related to material fatigue and failure prediction.

[⬆️ Back to the Top](#ue4-numpy)

---