### 👨‍💻 Solutions 2.2: Working with Array Attributes

Now let's practice examining and manipulating array attributes. Complete the following tasks:

#### **Shape and Size Exploration:**

1. Create a 3×4 array of random integers and examine its `shape`, `size`, and `ndim` attributes.
2. Create a 2×3×4 array of zeros and calculate how many elements it contains by multiplying the dimensions from the `shape` attribute.
3. Create an array with shape (5, 5) and print its total size in bytes using the `nbytes` attribute.

#### **Data Type Manipulation:**

4. Create an array of integers and check its `dtype` and `itemsize`.
5. Create the same array with `float32` data type and compare its memory usage (`nbytes`) with the integer array.
6. Create an array of values that exceed the range of `np.uint8` (0-255), convert it to `uint8`, and observe what happens.

#### **Dimensionality Operations:**

7. Create a 1D array and convert it to a column vector by adding a new axis using `np.newaxis`.
8. Create a 3×4 array and reshape it to a 2×6 array without changing the data using the `reshape()` method.
9. Create a 3D array with shape (2, 1, 3) and use the `squeeze()` method to remove dimensions of size 1.
10. Create three arrays with different shapes and dimensions, then print their `shape` and `ndim` attributes.

---


*Shape and size exploration:*



In [3]:
# 1. Create a 3×4 array of random integers and examine its shape, size, and ndim
import numpy as np

random_array = np.random.randint(0, 100, (3, 4))  # 3×4 array of random integers from 0 to 99
print(f"Array:\n{random_array}")
print(f"Shape: {random_array.shape}")  # Returns a tuple (3, 4)
print(f"Size: {random_array.size}")    # Total number of elements: 12
print(f"Number of dimensions: {random_array.ndim}")  # Number of axes: 2
# The shape tells us the size of each dimension, size gives the total element count

Array:
[[59 84 33 49]
 [14 22 62 99]
 [87 61  5 63]]
Shape: (3, 4)
Size: 12
Number of dimensions: 2


In [4]:
# 2. Create a 2×3×4 array of zeros and calculate how many elements it contains using the shape attribute
zeros_array = np.zeros((2, 3, 4))
element_count = zeros_array.shape[0] * zeros_array.shape[1] * zeros_array.shape[2]
print(f"Element count from shape: {element_count}")
print(f"Array size attribute: {zeros_array.size}")
# Both approaches give the same result: 24 elements

Element count from shape: 24
Array size attribute: 24


In [5]:
# 3. Create an array with shape (5, 5) and print its total size in bytes
array_5x5 = np.ones((5, 5))  # 5×5 array of ones
print(f"Array shape: {array_5x5.shape}")
print(f"Element size in bytes: {array_5x5.itemsize}")  # Size of each element
print(f"Total size in bytes: {array_5x5.nbytes}")      # Total memory used
# nbytes equals size × itemsize (25 elements × 8 bytes for float64)

Array shape: (5, 5)
Element size in bytes: 8
Total size in bytes: 200


*Data Type Manipulation:*

In [6]:
# 4. Create an array of integers and check its data type and itemsize
int_array = np.array([1, 2, 3, 4, 5])
print(f"Array: {int_array}")
print(f"Data type: {int_array.dtype}")      # Likely int64
print(f"Item size in bytes: {int_array.itemsize}")  # Likely 8 bytes for int64
# The itemsize tells us how many bytes each element uses in memory

Array: [1 2 3 4 5]
Data type: int64
Item size in bytes: 8


In [7]:
# 5. Create the same array with float32 data type and compare its memory usage (nbytes) with the integer array
float32_array = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(f"Integer array - dtype: {int_array.dtype}, nbytes: {int_array.nbytes}")
print(f"Float32 array - dtype: {float32_array.dtype}, nbytes: {float32_array.nbytes}")
print(f"Memory difference ratio: {int_array.nbytes / float32_array.nbytes:.2f}x")
# float32 uses half the memory of int64 or float64

Integer array - dtype: int64, nbytes: 40
Float32 array - dtype: float32, nbytes: 20
Memory difference ratio: 2.00x


In [8]:
# 6. Create an array of values that exceed the range of np.uint8 (0-255), convert it to uint8, and observe what happens
large_values = np.array([100, 200, 300, 400, 500])
uint8_values = large_values.astype(np.uint8)
   
print(f"Original values: {large_values}")
print(f"Converted to uint8: {uint8_values}")
print("Observation: Values that exceed the uint8 range (0-255) wrap around due to overflow.")
# Values above 255 wrap around: 300 becomes 44 (300 - 256), 400 becomes 144, etc.

Original values: [100 200 300 400 500]
Converted to uint8: [100 200  44 144 244]
Observation: Values that exceed the uint8 range (0-255) wrap around due to overflow.


*Dimensionality Operations:*

In [9]:
# 7. Create a 1D array and convert it to a column vector by adding a new axis
array_1d = np.array([1, 2, 3, 4])  # Shape: (4,)
column_vector = array_1d[:, np.newaxis]  # Adds a new axis at position 1
# Alternative: column_vector = array_1d.reshape(-1, 1)
   
print(f"1D array shape: {array_1d.shape}")        # (4,)
print(f"Column vector shape: {column_vector.shape}")  # (4, 1)
print(f"Column vector:\n{column_vector}")
# The np.newaxis is a special index that creates a new dimension of size 1

1D array shape: (4,)
Column vector shape: (4, 1)
Column vector:
[[1]
 [2]
 [3]
 [4]]


In [10]:
# 8. Create a 3×4 array and reshape it to a 2×6 array without changing the data
array_3x4 = np.arange(12).reshape(3, 4)  # 3×4 array with values 0-11
array_2x6 = array_3x4.reshape(2, 6)      # Reshape to 2×6
   
print(f"Original 3×4 array:\n{array_3x4}")
print(f"Reshaped 2×6 array:\n{array_2x6}")
# When reshaping, the total number of elements must remain the same (12)

Original 3×4 array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped 2×6 array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [11]:
# 9. Create a 3D array with shape (2, 1, 3) and use the squeeze method to remove dimensions of size 1
array_3d = np.array([[[1, 2, 3]],
                     [[4, 5, 6]]])  # Shape: (2, 1, 3)
print(f"Original shape: {array_3d.shape}")
   
squeezed_array = array_3d.squeeze()  # Removes dimensions of size 1
print(f"After squeeze, shape: {squeezed_array.shape}")  # (2, 3)
print(f"Squeezed array:\n{squeezed_array}")
# squeeze() removes all dimensions of size 1, making the array more compact

Original shape: (2, 1, 3)
After squeeze, shape: (2, 3)
Squeezed array:
[[1 2 3]
 [4 5 6]]


In [12]:
# 10. Create three arrays with different shapes and dimensions, then print their shapes and ndim
array_1d = np.array([1, 2, 3])              # 1D array
array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60]])         # 2D array
array_3d = np.zeros((2, 3, 2))              # 3D array
    
print(f"1D array - shape: {array_1d.shape}, ndim: {array_1d.ndim}")
print(f"2D array - shape: {array_2d.shape}, ndim: {array_2d.ndim}")
print(f"3D array - shape: {array_3d.shape}, ndim: {array_3d.ndim}")
# ndim gives the number of dimensions or axes in the array
# 1D arrays have ndim=1, 2D arrays have ndim=2, etc.

1D array - shape: (3,), ndim: 1
2D array - shape: (2, 3), ndim: 2
3D array - shape: (2, 3, 2), ndim: 3
